### ISSUE TITLE
Tampermonkey's popup issues if in "Extra menu" and "Check for userscript update" is clicked

### ISSUE THREAD

**Issue by makyen** [Tampermonkey/tampermonkey#1181]
## Expected Behavior
Normal display of popup with "Enabled" at the top, which is visible without scrolling.

## Actual Behavior
There is a `<div id="status" class="action status"></div>` at the top of the popup with the CSS:

```
body > div.action.status {
    position: relative;
    height: 100%;
}
```
which causes a large amount of vertical blank space. I have not looked into the structure or what else is being done, but just removing/disabling the `height: 100%;` is sufficient to resolve the issue.

Screenshot of the popup:
[![Screenshot of the popup with large blank area](https://i.stack.imgur.com/emL1S.png)](https://i.stack.imgur.com/emL1S.png)

If the popup is scrolled down, then the normal popup contents are shown (i.e. the "Enabled", list of userscripts which match the current URL, etc).

## Specifications

- Firefox: 86.0.1 (64-bit)
- TM: v4.12.6132
- OS: Win 10 x64

## Script
I have nearly 100 userscripts installed, but the exact scripts installed shouldn't matter. However, I did not see this happen on pages where no scripts were running, or could be running. I also did not see it on pages where there was only 1 userscript enabled and one disabled. I see it when the popup is opened for tabs where there are 20 to 50 userscripts which match the URL for the tab.

**Comment by derjanb** [comment]
Confirmed. Please add this to the "Custom CSS" setting to workaround the issues until a new version is released:

```CSS
body > div.action.status {
height: unset
}
```

![image](https://user-images.githubusercontent.com/767504/111587256-3ce55600-87c2-11eb-85ae-a8afbe1e242e.png)

**Comment by derjanb** [comment]
Should be fixed at the [latest BETA version](https://www.tampermonkey.net/?browser=firefox).

**Comment by EverEve** [comment]
Hello, in current beta I'm still experiencing this problem when the following occurs:

- Place the button in the "Extra menu" (Firefox interface)
- Click on the "Utilities" menu item
- Click on the "Check for userscript update"

Thanks
