### ISSUE TITLE
menu hotkeys not working sometimes

### ISSUE THREAD

**Issue by Owyn** [Tampermonkey/tampermonkey#1270]
(Please fill out the issue template with your details)

## Expected Behavior
you open TM menu, press hotkey, it works

## Actual Behavior
you open TM menu, press hotkey, it doesn't work, so you have to click it with mouse to work

## Specifications

- Chromium: FF 89.0.1
- TM: v4.13.6136
- OS: Win 10

## Script

(Please give an example of the script if applicable.)

https://github.com/Owyn/Universal_Dark_Theme/raw/master/uni_dark_theme.user.js 

screen: 

![image](https://user-images.githubusercontent.com/1309656/122922468-53c0b900-d36c-11eb-8290-48aa37e9c5cb.png)

console errors:

they seem to be same errors on different websites when it happens:

```
15:13:40.200 Error: Promised response from onMessage listener went out of scope ExtensionMessagingService.js:89:34

15:13:40.200 Error: Promised response from onMessage listener went out of scope 2 init.js:79:27

15:13:58.180 Error: Promised response from onMessage listener went out of scope common.js:4:491
```

**Comment by derjanb** [comment]
Should be fixed at 4.14.6141

**Comment by Owyn** [comment]
I've noticed that this issue is back again


    Chromium: FF 119.0.1
    TM: v4.19
    OS: Win 10

**Comment by Owyn** [comment]
TM V 5.0.0 - same issue, sometimes when I open the TM menu - it's just not in the focus or smth cuz no hotkeys are working

**Comment by derjanb** [comment]
Can you please check TM BETA 5.1.6193 and tell me whether this still happens. Do you still see "Error: Promised response from onMessage listener went out of scope" in this case?

Thanks.

**Comment by Owyn** [comment]
> Can you please check TM BETA 5.1.6193 and tell me whether this still happens. Do you still see "Error: Promised response from onMessage listener went out of scope" in this case?
> 
> Thanks.

yes, it happens as well, just tried it - pressed T on the menu once, then tried again - and no reaction, also no errors in the console

**Comment by Owyn** [comment]
same in stable  5.1.1 2024-04-22
after the `Resolved issues related to menu commands that were unregistered instantly` fix, 

a sureway to reproduce it is to open the menu - use a hotkey, then repeat, after one or two repeats - the hotkey stops working
