### ISSUE TITLE
Scripts don't run if scripts have been blocked with Brave Shields

### ISSUE THREAD

**Issue by is-this-c** [Tampermonkey/tampermonkey#1422]
I have checked that this problem doesn't exist in Violentmonkey.

Brave: 1.35.101
Chromium: 98.0.4758.87
TM: 4.14
OS: Windows 11

**Comment by derjanb** [comment]
This is maybe fixed at 4.18.6163 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx))

Can you please retry? Thanks.

**Comment by is-this-c** [comment]
> This is maybe fixed at 4.18.6163 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx))
> 
> Can you please retry? Thanks.

Unfortunately, Tampermonkey BETA from Chrome Web Store (4.18.6163) doesn't fix this issue.
