### ISSUE TITLE
Tampermonkey broke Firefox's built in XML document viewer

### ISSUE THREAD

**Issue by jcunews** [Tampermonkey/tampermonkey#1480]
(Please fill out the issue template with your details)

## Conditions
Use below do-nothing script in Firefox, and open below XML document.

https://www.w3schools.com/xml/cd_catalog.xml

## Expected Behavior
XML document is properly presented using Firefox's built in XML document viewer.

## Actual Behavior
The injection of the do-nothing script broke Firefox's built in XML document viewer.  
Causing the XML document data be treated as HTML data.  
It does not matter what the script does or does not do.

## Specifications

- Firefox: 91.0
- TM: 4.16.6160
- OS: Windows 7 SP2 x64

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name Do-Nothing
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match https://www.w3schools.com/*
// @grant none
// ==/UserScript==

(() => {
  //does nothing
})()
```

**Comment by derjanb** [comment]
If using TM 4.18+ there is workaround for now: set Sandbox Mode to "Force JavaScript", "JavaScript+DOM" or "Force DOM"

([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment]
Note: this comment menitions another workaound -> https://github.com/Tampermonkey/tampermonkey/issues/452#issuecomment-1145714320

**Comment by tomasz-q** [comment]
The workaround with Security settings is working partially, i.e. XML format is preserved, but one of my scripts which depends on jQuery and $.ajax stopped working.

Another workaround with blacklisting XML URLs used to work in older Tampermonkey versions. It does not work in 4.18.0 though.

**Comment by nematsakis** [comment]
I can confirm that the workaround of blacklisting XML sites in the security settings is not working in 4.18.0 and 4.18.1.  The Tampermonkey menu in the browser shows that the site is "Blacklisted by security settings" but the XML document viewer is still broken.

**Comment by derjanb** [comment]
Finally! 😅

Should be fixed at 4.19.6179 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by nematsakis** [comment]
Confirming that the fix works for me.  Tampermonkey v4.19.6179, Firefox 110.0, macOS 12.6.3 (21G419)

**Comment by nematsakis** [comment]
When will 4.19 be released? When I look at the [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) site, it still shows the current version as 4.18.1.

**Comment by SVNKoch** [comment]
Can confirm too, works in beta 4.19 but didn't in 4.18. Thanks for fixing!

**Comment by elisimpson** [comment]
Seems to be broken again even with the workaround from above. Latest Firefox and beta Tampermonkey

**Comment by derjanb** [comment]
> EDIT: with further research another extension is causing the problem... Bitwarden. No idea how to fix that

Not sure if this is possible, but to exempt XML pages in Bitwarden might fix the issue.
