### ISSUE TITLE
[Firefox] Have to keep reinstalling TM

### ISSUE THREAD

**Issue by madcollectordev** [Tampermonkey/tampermonkey#1553]
If I install Tampermonkey in Firefox, everything runs OK for a few days.
Then, after a random while (maybe linked to a FF update?) userscripts don't run anymore, and the Tampermonkey icon won't do anything except try and fail to load the menu, only displaying a loading icon.
I have then to remove and reinstall tampermonkey from Mozilla's add-ons page and my favourite userscripts. It works again for a few days, then goes wonky again, and again.

## Expected Behavior
Userscripts execute
Clicking on the Tampermonkey icon loads the Menu

## Actual Behavior
No userscripts run
clicking on the icon only diplays a "loading" icon, not the menu
![image](https://user-images.githubusercontent.com/34870193/179248172-0ccab5ed-61db-4e37-b218-5b3b0c1c126f.png)

## Specifications
- Firefox 102.0.1 (64 bits)
- TM: 4.17.6161
- OS: Windows 8.1

## Script
All scripts

**Comment by derjanb** [comment]
I guess this is a duplicate of #1384

Please try the fix explained here: https://github.com/Tampermonkey/tampermonkey/issues/1186#issuecomment-1151485354

**Comment by derjanb** [comment]
Can you please check the console for errors?

**Comment by madcollectordev** [comment]
prep: error at storage type detection 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/rea/background.js", lineNumber: 19, columnNumber: 0, data: null, stack: "@moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/rea/background.js:19:36\n@moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/rea/background.js:19:285\n@moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/rea/background.js:21:385\n" }
[background.js:19:158](moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/rea/background.js)

Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/background.js", lineNumber: 360, columnNumber: 0, data: null, stack: "@moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/background.js:360:355\n@moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/background.js:360:431\n@moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/background.js:884:352\n@moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/background.js:884:356\n" }
[background.js:360](moz-extension://663b0698-b95c-432e-a344-5c2f5b889750/background.js)

​

**Comment by cvzi** [comment]
I have the problem that Tampermonkey fails to run [this script](https://greasyfork.org/en/scripts/377439-spotify-genius-lyrics/) on [https://open.spotify.com/](https://open.spotify.com/) until I either Restart Tampermonkey or reinstall Tampermonkey. I don't know if this is the same issue as this.

Here are my logs from the web developer console:
```logs
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:57:422
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:58:154
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:136:34
content: normal start event processing for l6qw7pne.mgq (1 to run) content.js:52:4
env: schedule "Spotify Genius Lyrics" for document-idle content.js:41:167
content: DOMContentLoaded content.js:51:165
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.8.0. (Reason: CORS request did not succeed). Status code: (null).
env: run "Spotify Genius Lyrics" now content.js:40:14
content: normal start event processing for l6qx2jsx.kt9 (0 to run) content.js:52:4
content: DOMContentLoaded content.js:51:165
content: load 2 content.js:51:256
XHRGEThttps://spclient.wg.spotify.com/metadata/4/track/2tTmW7RDtMQtBk7m2rYeSw?market=from_token
[HTTP/1.1 404 Not Found 0ms]

Error: Promised response from onMessage listener went out of scope 2 ExtensionMessagingService.js:89:34

```

And from `about:debugging#/runtime/this-firefox`

```log
scriptman: determineScriptsToRun @https://open.spotify.com/search/que background.js:586:247
scriptman: @include "/^https:\/\/open\.spotify\.com\/.*$/i" matched (faef4748-848f-42d1-9d9a-f5ba3f93797e) background.js:425:431
scriptman: determineScriptsToRun: found script  
Object { script: {…}, cond: {…} }
background.js:587:288
check Spotify Genius Lyrics for enabled:true background.js:591:395
webRequest: relaxing script-src 'self' 'unsafe-eval' blob: open.spotifycdn.com open-review.spotifycdn.com quicksilver.scdn.co www.google-analytics.com www.googletagmanager.com static.ads-twitter.com analytics.twitter.com s.pinimg.com sc-static.net https://www.google.com/recaptcha/ cdn.ravenjs.com connect.facebook.net www.gstatic.com sb.scorecardresearch.com pixel-static.spotify.com https://s3.amazonaws.com/ki.js/51746/b0R.js https://cl.qualaroo.com/ki.js/51746/b0R.js turbo.qualaroo.com optimize.google.com cdn.cookielaw.org geolocation.onetrust.com www.googleoptimize.com www.fastly-insights.com static.hotjar.com script.hotjar.com https://www.googleadservices.com/pagead/conversion_async.js https://www.googleadservices.com/pagead/conversion/ https://analytics.tiktok.com/i18n/pixel/sdk.js https://analytics.tiktok.com/i18n/pixel/identify.js https://analytics.tiktok.com/i18n/pixel/config.js https://www.redditstatic.com/ads/pixel.js 'sha256-WfsTi7oVogdF9vq5d14s2birjvCglqWF842fyHhzoNw=' 'sha256-KRzjHxCdT8icNaDOqPBdY0AlKiIh5F8r4bnbe1PQwss=' 'sha256-Z5wh7XXSBR1+mTxLSPFhywCZJt77+uP1GikAgPIsu2s=' script-src 'unsafe-inline' 'self' 'unsafe-eval' blob: open.spotifycdn.com open-review.spotifycdn.com quicksilver.scdn.co www.google-analytics.com www.googletagmanager.com static.ads-twitter.com analytics.twitter.com s.pinimg.com sc-static.net https://www.google.com/recaptcha/ cdn.ravenjs.com connect.facebook.net www.gstatic.com sb.scorecardresearch.com pixel-static.spotify.com https://s3.amazonaws.com/ki.js/51746/b0R.js https://cl.qualaroo.com/ki.js/51746/b0R.js turbo.qualaroo.com optimize.google.com cdn.cookielaw.org geolocation.onetrust.com www.googleoptimize.com www.fastly-insights.com static.hotjar.com script.hotjar.com https://www.googleadservices.com/pagead/conversion_async.js https://www.googleadservices.com/pagead/conversion/ https://analytics.tiktok.com/i18n/pixel/sdk.js https://analytics.tiktok.com/i18n/pixel/identify.js https://analytics.tiktok.com/i18n/pixel/config.js https://www.redditstatic.com/ads/pixel.js * * * 
Object { requestId: "1313", url: "https://open.spotify.com/search/que", originUrl: undefined, documentUrl: undefined, method: "GET", type: "main_frame", timeStamp: 1660318086504, tabId: 28, frameId: 0, parentFrameId: -1, … }
background.js:693:253
badge: set icon background.js:623:158
badge: set background.js:625:18
mh: request  
Object { method: "prepare", id: "l6qw7pne.mgq", topframe: true, types: (1) […], url: "https://open.spotify.com/search/que" }
  sender:  
Object { contextId: 1099511627846, id: "firefoxbeta@tampermonkey.net", envType: "content_child", url: "https://open.spotify.com/search/que", tab: {…}, frameId: 0 }
background.js:823:229
mh: request page: undefined extpage: false background.js:824:4
run script Spotify Genius Lyrics @ https://open.spotify.com/search/que background.js:604:396
badge: set icon background.js:623:158
badge: set background.js:625:18
scriptman: determineScriptsToRun @https://www.google.com/recaptcha/enterprise/anchor?ar=1&k=6LfCVLAUAAAAALFwwRnnCJ12DalriUGbj8FW_J39&co=aHR0cHM6Ly9vcGVuLnNwb3RpZnkuY29tOjQ0Mw..&hl=en&v=gWN_U6xTIPevg0vuq7g1hct0&size=invisible&cb=aat4r5r3bhph background.js:586:247
badge: set icon background.js:623:158
badge: set background.js:625:18
mh: request  
Object { method: "prepare", id: "l6qx2jsx.kt9", topframe: false, types: (1) […], url: "https://www.google.com/recaptcha/enterprise/anchor?ar=1&k=6L…en&v=gWN_U6xTIPevg0vuq7g1hct0&size=invisible&cb=aat4r5r3bhph" }
  sender:  
Object { contextId: 2336462209028, id: "firefoxbeta@tampermonkey.net", envType: "content_child", url: "https://www.google.com/recaptcha/enterprise/anchor?ar=1&k=6L…en&v=gWN_U6xTIPevg0vuq7g1hct0&size=invisible&cb=aat4r5r3bhph", tab: {…}, frameId: 17179869204 }
background.js:823:229
mh: request page: undefined extpage: false background.js:824:4
badge: set icon background.js:623:158
badge: set background.js:625:18
badge: set icon background.js:623:158
badge: set background.js:625:18

```

**Comment by derjanb** [comment]
@cvzi Your issue is fixed in this issue: https://github.com/Tampermonkey/tampermonkey/issues/1186#issuecomment-1151485354

**Comment by derjanb** [comment]
> prep: error at storage type detection
> Uncaught Exception 

Both happens when `localStorage` is accessed. I have no idea why this should fail. 

Do you still see this issue?

**Comment by madcollectordev** [comment]
Tampermonkey still fails to load on FF 110.0.1 (64 bits)
I don't see any error in the Inspect debug session, but this is what it look like
![image](https://user-images.githubusercontent.com/34870193/224249546-861cca24-cf64-475c-b9ea-ed1f79d6352c.png)

I will try and update TM

**Comment by Samurott1999** [comment]
I'm also having this issue. The firefox extension debugger has the following errors in the console:
prep: error at storage type detection NS_ERROR_ABORT: 
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:248
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:249
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:893
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:893
[background.js:249:65](moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js)
    and
   Uncaught NS_ERROR_ABORT: 
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:281
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:281
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:893
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:893
[background.js:281](moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js)
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:281
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:281
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:893
    <anonymous> moz-extension://5123d666-9cca-4533-baa8-9c7d94fba0a1/background.js:893
I'm running Tampermonkey version 4.19.0 on Firefox version 117.0 and have had to reinstall Tampermonkey every time I reopen Firefox.
Once I reinstall Tampermonkey, it no longer has any errors until the next time I close and reopen Firefox. The userscripts have to be reinstalled, but they work fine until then.

**Comment by derjanb** [comment]
It looks like this is caused by some Firefox storage issue and it has a lot of them -> https://bugzilla.mozilla.org/show_bug.cgi?id=1482662

Please try a new temporary profile. 

Tampermonkey only can use the API provided by Firefox and depends on a correctly working storage.
