### ISSUE TITLE
Illegal invocation when call structuredClone

### ISSUE THREAD

**Issue by 7nik** [Tampermonkey/tampermonkey#1569]
When a userscript has any grants other than `none`, calling the global function `structuredClone` throws an error.

## Expected Behavior
The function is successfully called.

## Actual Behavior
The call throws the error `Uncaught (in promise) TypeError: Illegal invocation`

## Specifications

- Chromium Version 103.0.5060.134 
- TM: v4.16.1
- OS: Arch Linux (64-bit)

## Script

```js
// ==UserScript==
// @name         Test structuredClone in TM
// @match        https://example.com/
// @grant        GM_addStyle
// ==/UserScript==

console.log(structuredClone({}));
```

**Comment by derjanb** [comment]
Should be fixed at 4.18.6167 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

**Comment by mr-d-r** [comment]
I still have this bug.
userscript.html?name=xxx Uncaught (in promise) TypeError: Failed to execute 'showSaveFilePicker' on 'Window': Illegal invocation
// @grant        GM_addStyle

and works fine when // @grant        none

tampermonkey 5.3.3
chrome Version 132.0.6834.160 (Official Build) (64-bit)

please fix.
thank you in advance
