### ISSUE TITLE
Unchecked runtime.lastError

### ISSUE THREAD

**Issue by liquidmetalrob** [Tampermonkey/tampermonkey#1628]
Tampermonkey is causing the following error to come up on any page, even one where it's not running a script, while it's running:

`Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

**Comment by FrutyX** [comment]
Yes, I am seeing this too, there are no details, only this error message.

(Google Chrome, latest)

**Comment by liquidmetalrob** [comment]
A workaround for now is to use Violentmonkey.

**Comment by derjanb** [comment]
Should be fixed at 4.19.6170 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by liquidmetalrob** [comment]
Thanks Jan for the quick fix

**Comment by liquidmetalrob** [comment]
It looks like the error is back. I'm getting it again on Tampermonkey Beta version 4.20.6187.
