### ISSUE TITLE
GM_download/GM_xmlhttpRequest onload not called after calling document.write from another script in Chrome (and other browsers)

### ISSUE THREAD

**Issue by LordEliasTM** [Tampermonkey/tampermonkey#1760]
(Please fill out the issue template with your details)

## Expected Behavior
GM_download:
- request is being made
- file is downloaded by the browser
- onload is called

GM_xmlhttpRequest:
- request is being made
- onload is called

## Actual Behavior
GM_download:
- request is being made
- file is downloaded by the browser
- onload is **NOT** called

GM_xmlhttpRequest:
- request is being made
- onload is **NOT** called

## Specifications

- Chrome: 111.0.5563.147
- TM: 4.19.6181 (BETA)
- OS: Windows 10 Pro 22H2

## Script
Install and activate both scripts at the same time
```js
// ==UserScript==
// @name         TM-1
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.tampermonkey.net/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=tampermonkey.net

// @grant        GM_xmlhttpRequest
// @grant        GM_download
// @run-at       document-start
// ==/UserScript==

(() => {
    document.open();
    document.write("Patching...");
    document.close();
})();
```
```js
// ==UserScript==
// @name         TM-2
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.tampermonkey.net/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=tampermonkey.net

// @grant        GM_xmlhttpRequest
// @grant        GM_download
// @run-at       document-start
// ==/UserScript==

(() => {
    console.info("before calling");

    GM_download({
        url: 'https://www.tampermonkey.net/images/ricon48.png',
        name: 'ricon48.png',
        onerror: (e) => {console.info(e);},
        onload: (e) => {console.info(e);}
    });
    GM_xmlhttpRequest({
        url: 'https://www.tampermonkey.net/images/ricon48.png',
        onerror: (e) => {console.info(e);},
        onload: (e) => {console.info(e);}
    })

    console.info("after calling");
})();
```

**Comment by LordEliasTM** [comment]
Maybe related to https://github.com/Tampermonkey/tampermonkey/issues/1614

**Comment by derjanb** [comment]
This should be fixed at 4.19.6182 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by LordEliasTM** [comment]
Scripts provided above are still not working even after updating to beta :/

**Comment by derjanb** [comment]
Just to be sure: Have you tried restarting Chrome? Content scripts are sometimes cached.

**Comment by LordEliasTM** [comment]
Confirmed. Everything works as expected now. Thanks!
