### ISSUE TITLE
Unable to sync with Google Drive

### ISSUE THREAD

**Issue by DavidGhetto** [Tampermonkey/tampermonkey#1762]
## Expected Behavior

When configuring userscipts sync to use Google Drive, it should be possible to log in to a Google account and export userscripts on Google Drive.

## Actual Behavior

When selecting the Google account to use, authentication fails, and the saved token cannot be revoked.

## Specifications

- Opera 97.0.4719.63 (Chromium 111.0.5563.147)
- TM: 4.15.6154
- OS: Windows 10 64-bit

When I choose a Google account to use with TM, I get the prompt about the permissions requested from the app, then when I click to allow it, I'm getting a generic error message and I can see a 401 error in the console.

Also if I try to to revoke the access token the access token from the utilities tab of TM, I get a 400 error, first it was with this payload:

```
{
  "error": "invalid_request",
  "error_description": "Token is not revocable."
}
```

Now I'm still getting a 400 error but with this 

```
{
  "error": "invalid_token"
}
```

**Comment by ilan0098** [comment]
Apperntly importing from Google Drive backups don't work either , hope someone fixes it soon

**Comment by derjanb** [comment]
> TM: 4.15.6154

Please try the beta from Google Chrome Web Store -> https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf

> Apperntly importing from Google Drive backups don't work either , hope someone fixes it soon

Import and export as well as sync are working fine here. Please check the extensions background page network tab for erroneous requests and add some more details. Thanks.

**Comment by eggbean** [comment]
I have been using Tampermonkey for years (on Chrome) and I am sure I used BrowserSync before and it worked fine, but after an OS reinstallation I have not been able to have it working. I've tried Google Sync as well, as I don't want to have to try to remember all the userscripts I use another time. However, all that happens is that the sync popup animation comes up and it just hangs like that, for both BrowserSync and Gooogle Drive sync.

**Comment by ilan0098** [comment]
> > TM: 4.15.6154
> 
> Please try the beta from Google Chrome Web Store -> https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf
> 
> > Apperntly importing from Google Drive backups don't work either , hope someone fixes it soon
> 
> Import and export as well as sync are working fine here. Please check the extensions background page network tab for erroneous requests and add some more details. Thanks.

even using the beta won't work for me , still shows infinite "google drive : 100%"

**Comment by derjanb** [comment]
Please check the background console for erroneous requests. Thanks.

**Comment by ilan0098** [comment]
[https://i.imgur.com/t5cuCaA.png](url)
I also tried using a different browser but it still doesn't work

**Comment by eggbean** [comment]
I don't get anything that seems relevant either:
![image](https://user-images.githubusercontent.com/815311/233735066-c5741dfc-1525-4087-88d2-15e3737d2f41.png)

**Comment by dennisat** [comment]
Same here

**Comment by NebularNerd** [comment]
Beta 4.19.6181 seems to be working for me on both Firefox and Chrome

**Comment by YourAutisticLife** [comment]
Beta 4.20.6185 hangs forever, both on "Browser Sync" and "Google Drive".

The console messages are as reported above.

Things I tried:

1. I disabled Tampermonkey Editors.
2. I hit "Restart Tampermonkey."
3. I uninstalled and reinstalled Tampermonkey Beta.
4. I restarted the browser.

Nothing works. I get a spinning wheel that does not go away. At one point, I even completely hosed Tampermonkey. That's why I had to uninstall and reinstall.

**Comment by derjanb** [comment]
The Userscript Sync section has a "Recent Sync Log" text field that shows what's going on.

![image](https://github.com/Tampermonkey/tampermonkey/assets/767504/9d42686a-5c22-48ba-9d75-644a1e5f0ad1)

**Comment by YourAutisticLife** [comment]
The log remained empty when I tried to sync.

**Comment by ayasechan** [comment]
I'm having the same problem.
Even if I reinstall chrome, I still can't sync to Google Cloud Drive.
After clicking the export button, the popup window loads indefinitely.
But there is no error in the developer tools and no xhr request is made.

Specifications information

chrome version: 115.0.5790.171
tampermonkey version: 4.20.6185
os version: Windows 11 Version 22H2 (Build 22621.1992)

**Comment by NebularNerd** [comment]
For those having issues I found you have to do the following (at least for me this works)

- Check the `Enable Usersync' and select your preferred method
- Click `SAVE` immediately after, it should then run the initial sync

For Google Drive and such it may open a new window/tab after you save if you have not authorised the link before, otherwise it should them run. For me whenever I restart Chrome there is a chance Tampermonkey will re-ask for permission to connect to Google Drive

**Comment by derjanb** [comment]
Should be fixed at 5.1.6193 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by NebularNerd** [comment]
Google drive is still being iffy with me, did backup/factory restore/revoke access token on Chrome. Got it linked to my drive account but still hanging/taking forever to sync. Weirdly making backups seems to work ok.

**Comment by derjanb** [comment]
> Weirdly making backups seems to work ok.

At least it's is working in general.  :-)

> but still hanging/taking forever to sync

Does the "Recent Sync Log" show any messages? Do you see errors at the background page console or failing network requests?

**Comment by NebularNerd** [comment]
Nothing reporting in Chrome's Developer Console or Network both are blank.

If I try running a sync it starts, it may process a file or two then hangs with the dialog box spinning away until you reload the page. I have similar issues with slow/patchy/hanging issues with OneDrive, maybe I'm just cursed. I'm happy to test again in the future.

Personally, I'm now running some hideous frankenstein-esque setup using TamperDav running off a SFTP-Drive mounted sftp server on my router, that ensures all my various systems and browsers have a central vault. I don't tend to update scripts on my laptops much, so they can just update when on the home network. That seems pretty bullet proof for my needs.

**Comment by emukus** [comment]
I'm also facing a similar issue. Cannot sync, backup or even revoke the access token to google drive. However, I was able to do so on a different browser using a different google account
