### ISSUE TITLE
Failed to execute 'showDirectoryPicker' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by bambooGHT** [Tampermonkey/tampermonkey#1876]
When grant is other than none, the call will report an error.

## Expected Behavior
The function is successfully called.

## Actual Behavior
Failed to execute 'showDirectoryPicker' on 'Window': Illegal invocation.

## Specifications
- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *
// @grant        GM_xmlhttpRequest
// ==/UserScript==

(function () {
  setTimeout(() => {
    const dom = document.createElement("button");
    dom.innerText = "click";
    dom.onclick = async () => {
      console.log(showDirectoryPicker);

      showDirectoryPicker({ mode: "readwrite" })
        .catch((e) => console.log(e))
        .then(() => console.log("ok"));
    };
    
    document.body.appendChild(dom);
  }, 1000);
})();
```

**Comment by derjanb** [comment]
Should be fixed at 5.0.6190 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by bambooGHT** [comment]
> Should be fixed at 5.0.6190 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))
> 
> Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`. Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons`
> 
> For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

No errors are reported now. Thank you.

**Comment by mr-d-r** [comment]
I still have this bug.

userscript.html?name=xxx Uncaught (in promise) TypeError: Failed to execute 'showSaveFilePicker' on 'Window': Illegal invocation
// @grant        GM_addStyle

and works fine when // @grant        none

tampermonkey 5.3.3
chrome Version 132.0.6834.160 (Official Build) (64-bit)

please fix.
thank you in advance.

**Comment by derjanb** [comment]
My test script worked fine at these Chrome version:

Version 134.0.6974.3
Version 133.0.6943.27
Version 132.0.6834.83
Version 131.0.6778.204

Please open a new issue and add more details on how to reproduce this.
Note: `showDirectoryPicker` is not available at `http` pages

```js
// ==UserScript==
// @name         showDirectoryPicker
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://*/*
// @grant        GM_addStyle
// ==/UserScript==

(function () {
  setTimeout(() => {
    const dom = document.createElement("button");
    dom.innerText = "click";
    dom.onclick = async () => {
      console.log(showDirectoryPicker);

      showDirectoryPicker({ mode: "readwrite" })
        .catch((e) => console.log(e))
        .then(() => console.log("ok"));
    };

    document.body.appendChild(dom);
  }, 1000);
})();
```
