### ISSUE TITLE
Instant Injection Mode does not work if one of the scripts requires a local file

### ISSUE THREAD

**Issue by Rootkit-** [Tampermonkey/tampermonkey#1910]
![image](https://github.com/Tampermonkey/tampermonkey/assets/5389279/fa72ead7-cd07-4d27-8376-285607ad2a6d)

I made an example script lol. Downgrading tampermonkey fixed it.

## Expected Behavior
External files like
// @require file://W:\down\py\Tamper\jquery-3.6.1.js
// @require file://W:\down\py\Tamper\hoefunc.js
// @require file://W:\down\py\Tamper\waitForKeyElements.js

## Actual Behavior
They don't load.

## Specifications
Version 119.0.6045.106 (Official Build) (64-bit)

## Script

(Please give an example of the script if applicable.)

```// ==UserScript==
// @name         !Google
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description
// @author       Hoe
// @match        https://www.google.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=google.com
// @require file://W:\down\py\Tamper\jquery-3.6.1.js
// @require file://W:\down\py\Tamper\hoefunc.js
// @require file://W:\down\py\Tamper\waitForKeyElements.js
// @require file://W:\down\py\Tamper\jquery.nicescroll.js
// @run-at  document-end
// @grant	GM_addElement
// @grant	GM_addStyle
// @grant	GM_download
// @grant	GM_getResourceText
// @grant	GM_getResourceURL
// @grant	GM_info
// @grant	GM_log
// @grant	GM_notification
// @grant	GM_openInTab
// @grant	GM_registerMenuCommand
// @grant	GM_unregisterMenuCommand
// @grant	GM_setClipboard
// @grant	GM_getTab
// @grant	GM_saveTab
// @grant	GM_getTabs
// @grant	GM_setValue
// @grant	GM_getValue
// @grant	GM_deleteValue
// @grant	GM_listValues
// @grant	GM_addValueChangeListener
// @grant	GM_removeValueChangeListener
// @grant	GM_xmlhttpRequest
// @grant	GM_cookie
// @grant	window.onurlchange
// @grant	window.close
// @grant	window.focus
// ==/UserScript==
/* globals jQuery, $, waitForKeyElements,  findpos,  GoTo,  removeThis,  clickz,  copyToClipboard,  qsit ,  containsAnyString,  containsAnyStringLower,  containsAnyTrue,  triggerEvent,  replaceVal,  addFloatButtonss,  CreateLinkButton,  waitforclickthis,  sexyclick,  ClickThis,  getInnermostHover,  RecursiveUnbind,  saveData,  appendStyleToDocument*/

var debugg = true;

waitForKeyElements ("body", wait1);

function wait1(jNode) {
	cl('LOADING')
	const a = document.createElement("div");
	a.style ="font-size:100px;"
	a.textContent = "FUCCCCCCCCCCK"
 jNode[0].append(a)
}



function ci(variable) {
    if(debugg){
		console.info(variable);
    }
}
function ce(variable) {
    if(debugg){
		console.error(variable);
    }
}
function cw(variable) {
    if(debugg){
		console.warn(variable);
    }
}
function ct(variable) {
    if(debugg){
		console.trace(variable)
    }
}
function cc() {
    console.clear();
}
function cl(variable){
    if(debugg){
        console.log(variable)
    }
}
```

**Comment by derjanb** [comment]
Requiring local files is working fine here with Tampermonkey 5.0.0 and Chrome 119.0.6045.200.

Please try to disable and re-enable local file access. Do you see errors being logged at the page or background page console?

**Comment by stanislav-atr** [comment]
Same here on Chrome 119.0.6045.199 (Official Build) (x86_64). Resetting local file permissions didn't help, but downgrading to 4.19.0 did.
<details><summary>Script:</summary>

```
// ==UserScript==
// @name AdGuard Extra Watch
// @namespace    adguard
// @version      1.0.482
// @description AdGuard Extra is designed to solve complicated cases when regular ad blocking rules aren't enough.
// @homepageURL  https://adguard.com/
// @author       AdGuard
// @require      file:///Volumes/Work/adguard-extra/build/dev/userscript/adguard-extra-debug.user.js
// @match        *://*/*
// @grant        unsafeWindow
// @run-at       document-start
// ==/UserScript==
```
</details><br/>

**Comment by derjanb** [comment]
Hmm, still can't reproduce. The script is loaded any executed as ususal.

Do you see a network request to the local script? Are there any errors logged at the background page console?

![image](https://github.com/Tampermonkey/tampermonkey/assets/767504/d0fb660e-fef0-4d61-ba2f-9e0a9298d5f0)

**Comment by stanislav-atr** [comment]
I do not see this request in a network tab and there are no errors on Tampermonkey's background page.

**Comment by derjanb** [comment]
Do you have Instant Injection enabled?

**Comment by stanislav-atr** [comment]
@derjanb after the update, the inject mode dropped to its default value, and reverting it to`Instant` does not resolve the issue. Issue persists with any of the `Allow scripts to access local files` option values.

**Comment by derjanb** [comment]
Should be fixed at 5.0.6191 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please wait for the review being done and install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by pilgerone** [comment]
Version v5.1.6194 here and the bug is back, apparently.

I have a script that overrides the window.alert() function and it started to behave erratically. It only works once in every, idk, 20 page loads. Sadly I can't tell exactly when did this start cause I haven't use this particular script in a couple of months.

So I took all the scripts out from my local @require and embedded them directly into Tampermonkey's editor and it's working perfectly.

Any thoughts?

**Comment by derjanb** [comment]
This issue was about "Instant mode" injection not working at all when a local file was `@require`d. There is no fix except not using local files if real instant execution is required because loading the local file takes time.
