### ISSUE TITLE
Relative externals (`@require` and `@resource`) don't load

### ISSUE THREAD

**Issue by HenryGessau** [Tampermonkey/tampermonkey#2201]
## Expected Behavior
Scripts run when I visit a matching site

## Actual Behavior
Scripts do not run

## Specifications

- Firefox: `v131.0.3` (64-bit)
- TM: `v5.3.1`
- OS: Windows 11

## Script

One of many that I use:
https://github.com/murdos/musicbrainz-userscripts/blob/master/discogs_importer.user.js

**Comment by vitoo** [comment]
i guess its the @require 

![image](https://github.com/user-attachments/assets/3b0bc7af-559c-455b-a3fa-1980638c804e)

**Comment by psychoadept** [comment]
I've seen with a couple of site-specific scripts, too. I'd noticed in the Beta and it was fixed when I switched back to 5.3.0.

**Comment by kellnerd** [comment]
For the Discogs script it seems to be caused by the relative `@require` statements no longer working as expected.

**Comment by derjanb** [comment]
Yes, relative externals are broken. The workaround for now is to make them "more" absolute: either with a starting slash (only the host is relative) or as fully qualified URL.

Sorry for any inconvenience.

**Comment by derjanb** [comment]
Should be fixed at 5.3.6215 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by ppkhoa** [comment]
Just to clarify, 5.3.6215 isn't available yet? Firefox beta [xpi](https://www.tampermonkey.net/xpi/firefox-current-beta.xpi) still installs version 5.3.6213

**Comment by HenryGessau** [comment]
From the release notes, it looked to me like `5.3.2` would fix this.
However, I just tried it and it still doesn't work for me.

![image](https://github.com/user-attachments/assets/8bf42343-69b3-4682-9425-9adf482e1504)

**Comment by HenryGessau** [comment]
Now I downgraded back to `5.1.1` and it no longer works. What have I done? 😢

**Comment by HenryGessau** [comment]
I am able to get beta version `5.3.6216` working. Phew! 😅

**Comment by derjanb** [comment]
> From the release notes, it looked to me like 5.3.2 would fix this. However, I just tried it and it still doesn't work for me.

You have to re-install or reset the script. Warning: a reset deletes the script's storage.

![image](https://github.com/user-attachments/assets/f564d488-898b-4486-81fe-87892c23ce85)
