### ISSUE TITLE
Infinite "Please wait" while installing a script on Chrome

### ISSUE THREAD

**Issue by redweller** [Tampermonkey/tampermonkey#2285]
## Expected Behavior: script is installed.
People are having trouble installing a userscript on Chrome. This userscript gave no issues in the past, and it still can be successfully installed on Edge and FF.

## Actual Behavior: infinite "Please wait" window
When clicking the link to the script, TM opens the import tab and says "Please wait", then a file save dialogue pops. After that the Please wait message remains forever. This actually happens whenever the script is loaded - via link, via file, or if I manually copy paste it, change the version to a lower one and try updating. But if I copy-paste the script, it works. The other scripts I have tested are installed as usual.

## Specifications
- Chrome: 131.0.6778.109
- TM: i.e. 5.3.3
- OS: Win11

## Script
```js
// ==UserScript==
// @name         betteR20-beta-5etools
// @namespace    https://5e.tools/
// @license      MIT (https://opensource.org/licenses/MIT)
// @version      1.35.186.13
// @updateURL    https://raw.githubusercontent.com/redweller/betterR20/dev-beta/dist/betteR20-5etools.meta.js
// @downloadURL  https://raw.githubusercontent.com/redweller/betterR20/dev-beta/dist/betteR20-5etools.user.js
// @description  Enhance your Roll20 experience
// @author       5egmegaanon/astranauta/MrLabRat/TheGiddyLimit/DBAWiseMan/BDeveau/Remuz/Callador Julaan/Erogroth/Stormy/FlayedOne/Cucucc/Cee/oldewyrm/darthbeep/Mertang/Redweller

// @match        https://app.roll20.net/editor
// @match        https://app.roll20.net/editor#*
// @match        https://app.roll20.net/editor?*
// @match        https://app.roll20.net/editor/
// @match        https://app.roll20.net/editor/#*
// @match        https://app.roll20.net/editor/?*

// @grant        unsafeWindow
// @run-at       document-start

// @grant        GM_webRequest
// ==/UserScript==
```

**Comment by redweller** [comment]
Update: I've emptied my TM trash bin, and the script can be installed again. But any update operation leads to the same error, Below is the console output that happens when I just try to check for updates. In this case, it doesn't show the "download file" dialog, and the two subsequent console messages don't appear, just the "Please wait..." stuck forever

![image](https://github.com/user-attachments/assets/818413ea-d679-4c22-aaf6-73143eae59fd)

**Comment by redweller** [comment]
Some further research showed that the issue is indeed only related to script updates, and depends entirely on the current script, the one it's being updated to seems irrelevant. Also, as a hypothesis, this happens when the current script exceeds 30Mb size. I'm not absolutely sure, but it seems like it.

**Comment by redweller** [comment]
Also, Im sorry for the initial confusion. It's just the first person to report this said they were trying to "install" the script, so it didn't occur to me to explicitly check the fresh install.

**Comment by derjanb** [comment]
> Also, Im sorry for the initial confusion. 

No problem. I can reproduce it now...

**Comment by derjanb** [comment]
Should be fixed at 5.4.6224 

Please install [Tampermonkey BETA](https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf) or force update it at the extensions page `chrome://extensions`.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by Black-Platypus** [comment]
> or force update it at the extensions page `chrome://extensions`

How/where?
I only see the general "Update" button at the top (with the developer mode buttons "load unpacked" and "pack extension"), but that still leaves me at the regular 5.3.3

**Comment by Black-Platypus** [comment]
I still get the same error on v5.4.6228 BETA when trying to import my exported scripts and settings from "Import from file" (that's where I encountered this error in the first place)
<img width="1920" height="940" alt="Image" src="https://github.com/user-attachments/assets/010d1ac3-3521-40fc-937c-13c112237297" />
It then fails to complete the import.  

Weirdly, background.js shows no errors or messages during this.
options.html only shows the same message with a prefix:
<img width="744" height="96" alt="Image" src="https://github.com/user-attachments/assets/12f8c002-9024-40af-a014-1d2b74f1406a" />

**Comment by Black-Platypus** [comment]
The exported file in question is a 66 MB .txt export (it's JSON inside).
If needed: Is there a way I can provide it without it being publicly accessible?
