### ISSUE TITLE
[BUG] Tampermonkey prevents page loading forever

### ISSUE THREAD

**Issue by thomas-ross-aws** [Tampermonkey/tampermonkey#2456]
Thank you 🙇‍♀ for wanting to create an issue in this repository.
Before you do, please search the existing issues first as the problem may be already reported.

## Actual Behavior
Around 24 hours after enabling Tampermonkey, every page starts failing to load, they just spin forever. Even the Tampermonkey extension popup loads forever (similar to #2305). This occurs even with no userscripts installed and after re-creating my Firefox profile (keeping only places.sqlite). Restarting Firefox fixes it temporarily (5ish minutes?). Disabling and re-enabling the extension do not fix it, neither does re-installing the extension. There are no error logs when opening the console for the Tampermonkey extension, only some debug messages for "alarm:". There are no logs for the page when trying to load a page.

## Expected Behavior
Pages load properly with Tampermonkey enabled

## Steps to reproduce the issue

1. Install Tampermonkey
2. Wait 24 hours
3. Pages will no longer load

## Screenshots or Screencasts
N/A

## Environment (please complete the following information)

- Browser and Version: Firefox 139.0 (also happened with 138)
- Tampermonkey version:  5.3.3
- Operating System and Version: MacOS Sequoia

## Script

Please give an example of the script or its installation URL if applicable.
N/A

## Additional context
N/A

**Comment by derjanb** [comment]
I'm using 138.0.4 all day and havn't seen this issue.

Do you see errors at the background page console? https://www.tmnk.net/faq#Q600

**Comment by thomas-ross-aws** [comment]
Full logs from the background console after enabling debug logging:
```
alarm: init done Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } background.js:598:75
toea: register callback background.js:209:206
alarm: schedule[?|sync] Object { delayInMinutes: 1, periodInMinutes: 10, keepExistent: true } Array [] XXXXXXXXXX background.js:599:13
sri: md5 is supported background.js:536:354
sri: sha256 is supported background.js:536:354
badge: set icon _grey background.js:1039:400
alarm: schedule[?|blu] Object { when: 1748882425982, keepExistent: true } Array [] ZZZZZZZZZZ background.js:599:13
alarm: schedule[?|suc] Object { periodInMinutes: 60, keepExistent: true } Array [] YYYYYYYYYY background.js:599:13
sri: sha1 is supported background.js:536:440
sri: sha384 is supported background.js:536:440
sri: sha512 is supported background.js:536:440
toea: register callback 2 background.js:209:206
Storage: test -> start background.js:282:348
Storage: test -> set after 509ms background.js:282:420
Storage: test -> get after 510ms background.js:283:23
Storage: test -> remove after 1016ms background.js:283:279
toea: register callback 49 background.js:209:206
alarm: onAlarm[ZZZZZZZZZZ] Object { name: "ZZZZZZZZZZ", scheduledTime: 1748882328058, periodInMinutes: null } background.js:594:448
alarm: onAlarm[ZZZZZZZZZZ] mutex acquired Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } background.js:595:9
toea: register callback background.js:209:206
alarm: onAlarm[ZZZZZZZZZZ] mutex release background.js:595:296
toea: register callback 7 background.js:209:206
bg: ready! [sessionStart=false] background.js:1064:141
toea: run 64 callbacks background.js:209:319
upd: restart? false ( 186 seconds ago) background.js:429:344
mh: connect.method tabInfo contextId undefined tabId: 28 background.js:1002:74
badge: set icon background.js:1039:400
badge: set background.js:1041:190
mh: connect.method tabInfo contextId undefined tabId: 73 background.js:1002:74
mh: connect.method tabInfo contextId undefined tabId: 43 background.js:1002:74
badge: set icon background.js:1039:400
badge: set background.js:1041:190
Uncaught (in promise) Error: Attempt to postMessage on disconnected port
    e moz-extension://c8eaef07-4305-4808-90b0-842d087eb1a2/background.js:1001
    o moz-extension://c8eaef07-4305-4808-90b0-842d087eb1a2/background.js:1003
    r moz-extension://c8eaef07-4305-4808-90b0-842d087eb1a2/background.js:1004
    setReady moz-extension://c8eaef07-4305-4808-90b0-842d087eb1a2/background.js:209
    init moz-extension://c8eaef07-4305-4808-90b0-842d087eb1a2/background.js:1064
background.js:1001:387
badge: set icon background.js:1039:400
badge: set background.js:1041:190
badge: set icon background.js:1039:400
badge: set background.js:1041:190
badge: set icon background.js:1039:400
badge: set background.js:1041:190
badge: set icon background.js:1039:400
badge: set background.js:1041:190
badge: set icon background.js:1039:400
badge: set background.js:1041:190
badge: set icon background.js:1039:400
badge: set background.js:1041:190
badge: set icon background.js:1039:400
badge: set background.js:1041:190
badge: set icon background.js:1039:400
badge: set background.js:1041:190
badge: set icon background.js:1039:400
badge: set background.js:1041:190
badge: set icon background.js:1039:400
badge: set background.js:1041:190
alarm: onAlarm[XXXXXXXXXX] Object { name: "XXXXXXXXXX", scheduledTime: 1748880812636, periodInMinutes: 10 } background.js:594:448
alarm: onAlarm[XXXXXXXXXX] mutex acquired Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } background.js:595:9
alarm: emit[*|sync] Array [] background.js:595:411
alarm: onAlarm[XXXXXXXXXX] mutex release
```

`Error: Attempt to postMessage on disconnected port` looks the most relevant -- I haven't seen that one before, and I looked. It also seems like this might be correlated with switching network connections?

**Comment by z-aki** [comment]
same issue reported in  https://github.com/Tampermonkey/tampermonkey/issues/2474

**Comment by derjanb** [comment]
This should be fixed at 5.4.6226

Unfortunately the crx ist still inreview.
Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` **once the review is finished**.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by z-aki** [comment]
thanks!

this issue hasn't happened lately.

I'll update the addon when it's released properly.

cheers

**Comment by thomas-ross-aws** [comment]
It looks like this is still reproducible with BETA 5.4.6230. The console does not have the `Error: Attempt to postMessage on disconnected port` error anymore though

**Comment by thomas-ross-aws** [comment]
Here are some logs:

```
alarm: init done Object { XXXXXXXXXX: {…}, YYYYYYYYYY  {…}, ZZZZZZZZZZ: {…} } Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } background.js:607:177
Storage: use storage.local background.js:297:17
Storage: use memory background.js:297:17
alarm: schedule[?|sync] Object { delayInMinutes: 1, periodInMinutes: 10, keepExistent: true } Array [] undefined background.js:608:117
alarm: schedule[XXXXXXXXXX|sync] mutex acquired background.js:608:238
alarm: schedule[XXXXXXXXXX|sync] mutex release background.js:609:87
alarm: schedule[?|blu] Object { when: 1758309830277, keepExistent: true } Array [] undefined background.js:608:117
alarm: schedule[YYYYYYYYYY|blu] mutex acquired background.js:608:238
alarm: schedule[YYYYYYYYYY|blu] mutex release background.js:609:87
alarm: schedule[?|suc] Object { periodInMinutes: 60, keepExistent: true } Array [] undefined background.js:608:117
alarm: schedule[ZZZZZZZZZZ|suc] mutex acquired background.js:608:238
alarm: schedule[ZZZZZZZZZZ|suc] mutex release
Background event page was not terminated on idle because a DevTools toolbox is attached to the extension. background.html
alarm: onAlarm[YYYYYYYYYY] Object { name: "YYYYYYYYYY", scheduledTime: 1758309830277, periodInMinutes: null } background.js:604:27
alarm: onAlarm[YYYYYYYYYY] mutex acquired  Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } background.js:604:88
alarm: onAlarm[YYYYYYYYYY] mutex release background.js:604:375
alarm: onAlarm[XXXXXXXXXX] Object { name: "XXXXXXXXXX", scheduledTime: 1758309830277, periodInMinutes: 10 } background.js:604:27
alarm: onAlarm[XXXXXXXXXX] mutex acquired Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} }  Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } background.js:604:88
alarm: onAlarm[XXXXXXXXXX] mutex release
```

Unfortunately I cannot enable debug logging right now because (even after reinstall), the bug prevents the loading of the Tampermonkey settings page. I will enable debug logging as soon as it starts working again.

**Comment by euclio** [comment]
I experience this issue almost daily on my work machine. Happy to assist in any necessary debugging.

**Comment by derjanb** [comment]
Are you using "UserScripts API Dynamic" mode?

<img width="926" height="52" alt="Image" src="https://github.com/user-attachments/assets/74c0a63a-cb26-4f52-9386-9939c30be88d" />

**Comment by euclio** [comment]
No, I am using "UserScripts API".

**Comment by derjanb** [comment]
Thanks.

Can you please set the `Logging Level` to  `Debug`?

Then, when this issue happens, please go to `about:addons` and disable and re-enable Tampermonkey.
Now please inspect Tampermonkey's background page via `about:debugging#/runtime/this-firefox`.

Does Tampermonkey still prevent the pages from loading?
If so, does the background page console show any errors?

**Comment by thomas-ross-aws** [comment]
I just reproduced this with Debug logging level. There's not much more than what I provided previously unfortunately (https://github.com/Tampermonkey/tampermonkey/issues/2456#issuecomment-3313544056):

```
alarm: init done  Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } background.js:607:177
Storage: use storage.local background.js:297:17
Storage: use memory background.js:297:17
toea: register callback background.js:209:206
alarm: schedule[?|sync] Object { delayInMinutes: 1, periodInMinutes: 10, keepExistent: true } Array [] undefined background.js:608:117
alarm: schedule[XXXXXXXXXX|sync] mutex acquired background.js:608:238
sri: md5 is supported background.js:545:354
sri: sha256 is supported background.js:545:354
badge: set icon _grey background.js:1058:124
sri: sha1 is supported background.js:545:440
sri: sha384 is supported background.js:545:440
sri: sha512 is supported background.js:545:440
alarm: schedule[XXXXXXXXXX|sync] mutex release background.js:609:87
alarm: schedule[?|blu] Object { when: 1763752533216, keepExistent: true } Array [] undefined background.js:608:117
alarm: schedule[YYYYYYYYYY|blu] mutex acquired background.js:608:238
alarm: schedule[YYYYYYYYYY|blu] mutex release background.js:609:87
alarm: schedule[?|suc] Object { periodInMinutes: 60, keepExistent: true } Array [] undefined background.js:608:117
alarm: schedule[ZZZZZZZZZZ|suc] mutex acquired background.js:608:238
alarm: schedule[ZZZZZZZZZZ|suc] mutex release background.js:609:87
toea: register callback 10 background.js:209:206
```

This time I did exactly what you suggested: disabled/re-enabled Tampermonkey. It did still prevent pages from loading after re-enabling. No errors in the log as far as I can tell, that is the full log.

Also, I mentioned previously that it seemed to be correlated with switching network connections. That does not seem to be the case anymore, it happens randomly throughout the day (and is also fixed randomly, I do not see any patterns)

**Comment by euclio** [comment]
I captured a similar log:

[console-export-2025-11-24_10-22-30.log](https://github.com/user-attachments/files/23726249/console-export-2025-11-24_10-22-30.log)

**Comment by derjanb** [comment]
This might be fixed at 5.5.6232 (xpi in review). At least some more debug output is created to narrow the issue down further.

Please wait for the XPI being reviewed and install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` **once the review is finished**.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment]
Please install or update your Tampermonkey BETA version. There now is more debug output to get an idea what gets stuck and I added timeouts to some calls. So the issue migth resolve after 10 seconds when it gets stuck. This means, that a Firefox API call went wrong or didn't come back with a result. So script injection might fail.

**Comment by thomas-ross-aws** [comment]
Here are the logs from  5.5.6232. No user scripts installed. It did not auto-resolve after 10 seconds.

```
alarm: init done Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } Object { XXXXXXXXXX: {…}, YYYYYYYYYY: {…}, ZZZZZZZZZZ: {…} } background.js:610:177
Storage: use storage.local background.js:297:259
Storage: use memory background.js:297:259
toea: register callback background.js:209:206
alarm: schedule[?|sync] Object { delayInMinutes: 1, periodInMinutes: 10, keepExistent: true } Array [] undefined background.js:611:117
alarm: schedule[XXXXXXXXXX|sync] mutex acquired background.js:611:238
sri: md5 is supported background.js:548:354
sri: sha256 is supported background.js:548:354
badge: set icon _grey background.js:1064:124
bg: init user agent infos background.js:1089:375
sri: sha1 is supported background.js:548:440
sri: sha384 is supported background.js:548:440
sri: sha512 is supported background.js:548:440
alarm: schedule[XXXXXXXXXX|sync] mutex release background.js:612:87
alarm: schedule[?|blu] Object { when: 1764947362508, keepExistent: true } Array [] undefined background.js:611:117
alarm: schedule[YYYYYYYYYY|blu] mutex acquired background.js:611:238
bg: init script injection handling background.js:1091:390
alarm: schedule[YYYYYYYYYY|blu] mutex release background.js:612:87
alarm: schedule[?|suc] Object { periodInMinutes: 60, keepExistent: true } Array [] undefined background.js:611:117
alarm: schedule[ZZZZZZZZZZ|suc] mutex acquired background.js:611:238
alarm: schedule[ZZZZZZZZZZ|suc] mutex release background.js:612:87
bg: initialization of script injection handling took too long, continue anyway background.js:1092:40
bg: ready! [sessionStart=true] background.js:1092:163
toea: run 3 callbacks background.js:209:319
upd: restart? false ( 143 seconds ago) background.js:429:454

=== (I created a new tab) ===
badge: set icon background.js:1064:124
badge: set background.js:1066:107
badge: set icon background.js:1064:124
badge: set background.js:1066:107

=== (I pressed enter to load google.com) ===
scriptman: determineScriptsToRun @https://www.google.com/ background.js:693:450
```

**Comment by derjanb** [comment]
> bg: initialization of script injection handling took too long, continue anyway

This is the message that indicates that the timeout fired. 😭

After this message every request should continue to run. 🤔 Can you please check the network tab?

**Comment by thomas-ross-aws** [comment]
It's stopped reproducing itself for now, I will check as soon as it comes back.

In that log, the "bg: initialization of script injection handling took too long, continue anyway" actually happened _before_ i created a new tab where page loads got stuck. Does that matter?

**Comment by derjanb** [comment]
> Does that matter?

I guess yes. But it then means, that not Tampermonkey itself is blocking web requests, but FF didn't manage to complete the content script/dynamic userScript setup and that's why starts blocking new page loads.

When this happens do the network requests of other tabs work as expected?

BTW: What is your FF version in the meantime? I'm using 145.0.2 at two different PCs now and never saw this.

**Comment by derjanb** [comment]
Also, can you please try older version from https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/versions/

When did this start to happen? **IMPORTANT**: make backup before going back. 5.4.0 added a non-reversible storage migration.

**Comment by thomas-ross-aws** [comment]
> When this happens do the network requests of other tabs work as expected?

No, they don't. Every tab stops working.

> BTW: What is your FF version in the meantime? I'm using 145.0.2 at two different PCs now and never saw this.

Currently 144.0 on macOS. I've seen it on every version through 138.0.

> Also, can you please try older version

Yeah, I will give it a shot.

> When did this start to happen?

Probably a couple of weeks before I opened this issue, so early-mid May.

**Comment by battaglia01** [comment]
Having this problem here as well for the past few days. Things don't load, all tabs are broken, and if I turn Tampermonkey off they load immediately. I'm on Firefox Developer Edition, version 147.0b7 (aarch64), on macOS Sonoma 14.5. Maybe this is a Firefox Mac issue. What older version of this plugin works?

**Comment by hectorsouthern** [comment]
I see this issue on FF Version 146.0.1 (64-bit) and Tampermonkey V5.4.1, even with all scripts disabled.
Same behaviour - no tabs can load and Tampermonkey shows a spinning loading animation when I click on the extension.
Everything loads immediately once the extension is disabled.

**Comment by BenRemer** [comment]
I currently see this issue no matter what version of tapermonkey I install. I've grabbed old ones but still see the same problem seemingly randomly.

**Comment by t111** [comment]
I've been having this issue for months, until recently my colleague shared a fix with me: disabling the HTTP cache.

steps:

  1. in the address bar, type `about:config` and hit Enter
  2. click "Accept the Risk and Continue".
  3. in the search bar, type: `browser.cache.disk.enable`, a single preference row should appear. 
  4. the default value is true. Click the toggle button to set it to false.

the change takes effect immediately, and I'm not seeing the issue for a couple of days now. 

I hope this work for you guys too. If it doesn't, maybe try combining it with TM Beta version.

**Comment by derjanb** [comment]
Some users mentioned macOS. Is there anyone experiencing this problem under Windows or a Linux OS?

**Comment by nabellows** [comment]
> Some users mentioned macOS. Is there anyone experiencing this problem under Windows or a Linux OS?

Not to spam/distract from Linux/Windows replies, but I consistently had this issue and yes it was MacOS.

**Comment by eglyph** [comment]
Can confirm it's still an issue on the MacOS with the FF 149.0 and the BETA version of the extension. Disabling a file cache doesn't really help. The only difference is that BETA loads a widget and allows opening a dashboard. No userscripts are loaded. 
The issue is intermittent, sometimes it doesn't happen for days, sometimes it doesn't go away after days no matter how many times a browser is restarted.

**Comment by rmartinussen** [comment]
I'm pretty confident I am still experiencing this on MacOS 15.7.2, firefox 150.0.3, both latest FF tampermonkey version and beta. Has anyone found a better workaround than just toggling/disabling the extension or (and I haven't tested if this even helps either, honestly) *disabling the browser http cache*?

**Comment by jtrott** [comment]
Having the same issue on Waterfox 6.6.13 (aarch64) using TM 5.5.0 on macOS 26.5.

**Comment by Zweih** [comment]
Seeing this on Linux (CachyOS (arch btw)) on FF 151.0.3. No scripts installed, as well. Disabling it immediately loads pages.

**Comment by rad-orlowski** [comment]
> Having the same issue on Waterfox 6.6.13 (aarch64) using TM 5.5.0 on macOS 26.5.

Same here.

|Key|Value|
|---|---|
|TM| 5.5.0|
|System|maCOS 26.0.1|
|Browser|Firefox 151.0.4 (aarch64)|

**Comment by WhiverFichos** [comment]
> Some users mentioned macOS. Is there anyone experiencing this problem under Windows or a Linux OS?

I didn't see anyone using Windows, so [here](https://github.com/Tampermonkey/tampermonkey/issues/2836#issuecomment-5330948001) I am.

btw, [t111's approach](https://github.com/Tampermonkey/tampermonkey/issues/2456#issuecomment-3935709053) doesn't work to me (5.5.0)

> 3. in the search bar, type: `browser.cache.disk.enable`, a single preference row should appear.

**Comment by kupietools** [comment]
Having the same issue on MacOS Firefox, both TM 5.5.0 and 5.6.6239 beta. 

I have a root-cause trace for this on Firefox that might help narrow it down.

**Environment:** Firefox 153.0 (15326.7.15), macOS 12.7.6. Tampermonkey 5.5.0 (stable) and current Firefox 5.6.6239 beta build — both affected identically.

**What the Firefox Profiler shows during a live hang:** for the specific request that hangs, the network channel goes through a completely normal sequence — `AsyncOpen` → `BeginConnect` → cache check → `OnStartRequest` (i.e. the response headers have already arrived from the server) — all within under a second. It then suspends for the `onHeadersReceived` stage, where any extensions with blocking `webRequest` listeners are invoked (in my case: uBlock Origin, Ghostery, and Tampermonkey). For the hung request, there was no further marker of any kind for the rest of a ~60-second recording — no `Resume`, no `OnDataAvailable`, no `OnStopRequest`. It just stopped dead at that point. Other requests in the same recording went through the identical three-extension `onHeadersReceived` gate and resumed within single-digit milliseconds.

So this isn't a slow userscript or a network issue — Firefox has already received the response and is withholding it from the page because a blocking `onHeadersReceived` listener that was invoked never called back.

**Isolating it to Tampermonkey specifically:** disabling Tampermonkey (leaving uBlock Origin and Ghostery enabled) resolves it instantly and completely, every time. No other combination of disabling those three extensions seems to matter, only whether Tampermonkey is disabled.

**One detail I haven't seen mentioned elsewhere in this thread:** Tampermonkey's own in-extension "disabled" toggle (in its dashboard/settings) does **not** stop the hangs — it happens with zero userscripts installed/enabled and with Tampermonkey set to disabled inside its own settings screen. The only thing that stops it is disabling the extension entirely from Firefox's `about:addons` / Manage Extensions screen. That suggests the blocking `webRequest.onHeadersReceived` listener registration happens at background-script load time and isn't torn down by Tampermonkey's internal enable/disable state — only by the WebExtension itself being unloaded.

Making browser.cache.disk.enable false doesn't fix it for me, either.
