### ISSUE TITLE
Waiting too long (stuck) when getting a large ArrayBuffer content with GM_xhr

### ISSUE THREAD

**Issue by ccloli** [Tampermonkey/tampermonkey#279]
Example script: https://gist.github.com/ccloli/9c6c6ab484cfc78bddcaf656afc6cc73

When getting a large binary file as Arraybuffer with `GM_xmlhttpRequest`, browser will stuck. I checked `res`, seems that Tampermonkey stored response data as string, and transfer it to ArrayBuffer when requesting `res.response`. So if response data is too large, Tampermonkey would waste too much time and CPU resource to transfer it.

Here are some screenshots of test result:

Tampermonkey on Chrome
![Tampermonkey on Chrome](https://cloud.githubusercontent.com/assets/8115912/14403760/15f635c4-fe96-11e5-943d-96ffcac005d3.png)
Violentmonkey on Chrome
![Violentmonkey on Chrome](https://cloud.githubusercontent.com/assets/8115912/14403765/37d4a824-fe96-11e5-956c-e7f1d44deb83.png)
Tampermonkey on Firefox (however, I waited about 10 seconds until the music played)
![Tampermonkey on Firefox (however, I waited about 10 seconds until the music played)](https://cloud.githubusercontent.com/assets/8115912/14403769/67444790-fe96-11e5-9edb-c3f005ef56ae.png)
GreaseMonkey on Firefox
![GreaseMonkey on Firefox](https://cloud.githubusercontent.com/assets/8115912/14403774/831a4a64-fe96-11e5-98bb-a79e128ca039.png)

**Comment by hybridsong** [comment]
I have encountered such a problem.

**Comment by ccloli** [comment]
Hi again, I'm just reply here to describe it clearly :-)

As Tampermonkey also released in Edge, so I tested my script to ensure that is it supports Edge. It's a script like the script that posted here, use `GM_xmlhttpRequest` and set `responseType: "arraybuffer"` to get some large files, then store all of them into a Zip file and give it to user. Yeah I know it's a bit crazy because it's not a good way to do it in browser. Luckily it works fine on Edge, the only problem is often to see "The page is not responding". So I tested my code again, and paste full details here.

Test script: 
```js
// ==UserScript==
// @name         GM_xhr test
// @version      1.0
// @description  Get a large binary file as ArrayBuffer with GM_xhr
// @include      http://localhost/*
// @grant        GM_xmlhttpRequest
// @connect      localhost
// ==/UserScript==

// modify url and @connect if needed
var url = 'http://localhost/test.mp3';
console.log('Environment: '); // Surely, I input it by myself! :-)

GM_xmlhttpRequest({
    method: 'GET',
    url: url,
    responseType: 'arraybuffer',
    onload: function(res){
        var t = new Date();
        console.log('File loaded at ' + t);
        console.log('Elapsed time: ' + (t - ot) + 'ms');

        var response = res.response;
        var t2 = new Date();
        console.log('Get ArrayBuffer content at ' + t2);

        console.log('File size: ' + response.byteLength);
        console.log('Elapsed time: ' + (t2 - t) + ' ms');

        // play music, also check if pasted time is correct
        var blob = new Blob([response], {type: 'audio/mpeg'});
        var blobURL = URL.createObjectURL(blob);
        var audio = document.createElement('audio');
        audio.src = blobURL;
        audio.play();
        var t3 = new Date();
        console.log('Start playing at ' + t3);
        console.log('Elapsed time: ' + (t3 - t) + ' ms (since file loaded)');
    },
    onerror: function(res){
        console.log('Can\'t load file.');
    }
});
var ot = new Date();
console.log('Requested at ' + ot);
```

In Chrome, I tested Violent monkey, Tampermonkey Legacy and Tampermonkey BETA, their logs are showing below:
![Chrome with Violent monkey, Tampermonkey Legacy and Tampermonkey BETA](https://cloud.githubusercontent.com/assets/8115912/18223661/fe3f6a76-71f0-11e6-87bd-324ba4a8ea3b.png)

It seems that after `GM_xmlhttpRequest` called, it took about 2 seconds to enter `onload` function (and in TM Legacy it took about 4 seconds), it probably be transferring response data to extension or others, because it only took no more than 1 second to get file data from server. In this picture, background page takes 99 ms to get file, but when `onload` function called, it took about 3 s :
![qq 20160903155100](https://cloud.githubusercontent.com/assets/8115912/18223682/bf9070f8-71f1-11e6-8e4c-6732169c6bd3.png)

This also happens in Firefox, here are the logs of GreaseMonkey and Tampermonkey in Firefox:
![Firefox with GreaseMonkey and Tampermonkey](https://cloud.githubusercontent.com/assets/8115912/18223697/39703cdc-71f2-11e6-8531-8afc9ce0c509.png)

You can see the second request took about 30 seconds to get `ArrayBuffer`, because it said a script is busy:
![Firefox: a script on this page may be busy](https://cloud.githubusercontent.com/assets/8115912/18223712/8cc9e252-71f2-11e6-89d2-6873c211b3e9.png)
_(Sorry this screenshot is in Chinese, it said "A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue. Script: http://localhost/owncloud/:2")_

So it would probably because of transferring data from background page to content script, however you can still noticed that in latest Tampermonkey, it takes a lot of time to get the ArrayBuffer content after the `onload` function called.

I tried logging the `res` argument in `onload` function, looks like `res.response` is a getter function, then I checked `<function scope>` and saw the file data is assigned as string. So I guess the latest version Tampermonkey stores response data as string, and transfer it to ArrayBuffer when `res.response` is called. So I think that's probably the reason why the page getting stuck.
![Getter](https://cloud.githubusercontent.com/assets/8115912/18223832/1694b180-71f6-11e6-9fc6-b1ea4610ced6.png)

**Comment by derjanb** [comment]
Sorry for the delay. The fix required major changes that I had put off for too long.

However, the issue should be fixed at TM BETA 4.12.6124. 😅

I'm not sure the Chrome Webstore team will be able to review this version this year, but in the meantime, you can download it from [here](https://www.tampermonkey.net/crx/tampermonkey_beta_4_12_6124.crx).

**Comment by AlttiRi** [comment]
Not fixed.

With TM BETA 4.12.6123: lags, but file is downloaded.
With TM BETA 4.12.6123: no lags, but file is **not** downloaded. At all.

From [my issue](https://github.com/Tampermonkey/tampermonkey/issues/1107):
```js
// ==UserScript==
// @name        Issue 1107 (GM.xmlHttpRequest, 104 MB, gfycat.com)
// @namespace   Issues
// @match       https://github.com/Tampermonkey/tampermonkey/issues/1107
// @match       https://example.com/
// @grant       GM.xmlHttpRequest
// @connect     giant.gfycat.com
// ==/UserScript==

!async function() {
    console.log("downloading (104 MB)...");
    const response = await new Promise((resolve, reject) => {
        GM.xmlHttpRequest({
            method: "get",
            url: "https://giant.gfycat.com/ConfusedRecentGuppy.mp4", // 104 MB
            responseType: "blob",
            onload: resolve,
            onerror: reject,
        });
    });
    console.log("response:", response);

    const {response: blob} = response;
    downloadBlob(blob, "ConfusedRecentGuppy.mp4");
}();

function downloadBlob(blob, name) {
    const anchor = document.createElement("a");
    anchor.setAttribute("download", name || "");
    anchor.href = URL.createObjectURL(blob);
    anchor.click();
}
```

**Comment by derjanb** [comment]
@AlttiRi Hmm, I've double checked this with exactly this script and:

Windows 10 Pro 20H2
Chrome Version 87.0.4280.88 (Offizieller Build) (64-Bit)

Ubuntu 20.04
Chrome Beta Version 88.0.4324.50 (Official Build) beta (64-bit)
Chromium Version 87.0.4280.88 (Official Build) snap (64-bit)

and it works all the time: the log message is printed, it takes 10 to 15 seconds and the file becomes visible as browser download.

Do you see errors at the site's console or extension background page console?

**Comment by ccloli** [comment]
Well, it works fine from my side, got a mp4 file with 109,640,890 bytes and it matches content-length header. Maybe you can restart your browser and retry?


---原始邮件---
发件人:&quot;AlttiRi&quot;<notifications@github.com&gt;
发送时间:2020年12月31日 星期四 下午1:21
收件人:&quot;Tampermonkey/tampermonkey&quot;<tampermonkey@noreply.github.com&gt;
抄送:&quot;864907600cc&quot;<h@ccloli.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;
主题:Re: [Tampermonkey/tampermonkey] Waiting too long (stuck) when getting a large ArrayBuffer content with GM_xhr (#279)

Not fixed.
With TM BETA 4.12.6123: lags, but file is downloaded.
With TM BETA 4.12.6123: no lags, but file isnotdownloaded. At all.
Frommy issue:
// ==UserScript==//@nameIssue 1107 (GM.xmlHttpRequest, 104 MB, gfycat.com)//@namespaceIssues//@matchhttps://github.com/Tampermonkey/tampermonkey/issues/1107//@matchhttps://example.com///@grantGM.xmlHttpRequest//@connectgiant.gfycat.com// ==/UserScript==!asyncfunction(){console.log(&quot;downloading (104 MB)...&quot;);constresponse=awaitnewPromise((resolve,reject)=&gt;{GM.xmlHttpRequest({method:&quot;get&quot;,url:&quot;https://giant.gfycat.com/ConfusedRecentGuppy.mp4&quot;,// 104 MBresponseType:&quot;blob&quot;,onload:resolve,onerror:reject,});});console.log(&quot;response:&quot;,response);const{response:blob}=response;downloadBlob(blob,&quot;ConfusedRecentGuppy.mp4&quot;);}();functiondownloadBlob(blob,name){constanchor=document.createElement(&quot;a&quot;);anchor.setAttribute(&quot;download&quot;,name||&quot;&quot;);anchor.href=URL.createObjectURL(blob);anchor.click();}

－

**Comment by AlttiRi** [comment]
I get the `Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.` exception.
Because of `blob` is `undefined`.

Chrome 87.0.4280.88.

**Comment by AlttiRi** [comment]
Well, it works on example.com, but no [here](https://github.com/Tampermonkey/tampermonkey/issues/279) _now_.
![image](https://user-images.githubusercontent.com/16310547/103405635-ca70bc80-4b68-11eb-8685-b1612543babb.png)
`
VM333:3 Refused to connect to 'blob:https://github.com/ad885423-8cda-40c9-ae55-adfee981afc1' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://alive.github.com".
`

**Comment by ccloli** [comment]
Yep, I changed my test script to make it runs on GitHub, and get the same CSP error. I tested it with ViolentMonkey, and it works fine, seems it bypass the CSP limit.

That reminds me another userscript management extension named Guerilla Scripting that works on Pale Moon browser. Well the current version of Tampermonkey works better than that, since Guerilla Scripting doesn't solve the cross origin problem, so when you're trying to call `GM_xmlhttpRequest` with `arraybuffer`, it'll throw a cross origin error. So I guess that is why Tampermonkey uses an ugly way that receives binary data as string, then convert it to ArrayBuffer or Blob which introduce performance problem.

**Comment by derjanb** [comment]
> Well, it works fine on example.com, but not here (github.com) now (due to CSP).

I see. Thanks.

**Comment by derjanb** [comment]
Finally... [4.12.6125](https://www.tampermonkey.net/crx/tampermonkey_beta_4_12_6125.crx) (so at least hopefully 🙈😁)

**Comment by AlttiRi** [comment]
Works fine.

**Comment by ccloli** [comment]
Tested with Chrome 89.0.4378.0 canary with Tampermonkey BETA v4.12.6125, each file from my script can be downloaded successfully, and the file hashes are matched.
