### ISSUE TITLE
Chrome 52 breaks @require & window.localStorage

### ISSUE THREAD

**Issue by DakuTree** [Tampermonkey/tampermonkey#291]
Two bugs have popped up after updating to the recent Chrome Dev update (52.0.2723.2):
* `@require` doesn't seem to load properly anymore.  
  Loading jQuery via  `// @require      https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js` returns "Execution of script 'TEST-SCRIPT' failed! Cannot read property 'createElement' of undefined".
* window.localStorage seems to return "undefined" now (unsafeWindow still seems to work fine).

**Comment by ccd0** [comment]
Likely related: With Chrome 52, `window.scrollY` is undefined if `@grant` is not `none`. Tested with Chrome 52.0.2723.2 and both Tampermonkey 4.0.25 and Tampermonkey BETA 4.1.5222.

    // ==UserScript==
    // @name         window.scrollY bug
    // @namespace    Test
    // @version      0.1
    // @description  Test
    // @author       You
    // @match        http://www.example.com/
    // @grant        GM_getValue
    // ==/UserScript==

    alert(window.scrollY);

**Comment by ferongr** [comment]
It's fixed with the Beta. Thanks.

**Comment by ccd0** [comment]
@ferongr
Are you talking about the 4chan X beta? Because I'm still seeing this `window.scrollY` issue in Tampermonkey BETA, and I don't see an update since 4.1.5222 yet.

**Comment by ccd0** [comment]
And the same for `window.localStorage`, both are `undefined` if `@grant` is other than `none`.

**Comment by ferongr** [comment]
Sorry, brainfart, wrong issue.

**Comment by derjanb** [comment]
This should be fixed at the beta version: http://tampermonkey.net/changelog.php?version=4.1.5224&ext=gcal

**Comment by ccd0** [comment]
Can confirm that the `window.scrollY` issue I was having is fixed.
