### ISSUE TITLE
Middle mouse button (scroll) doesn't open script for edit

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Tampermonkey/tampermonkey#341]
After update browser to Chrome55 scroll doesn't open script for edit. Now I must go to TM option and edit script from this place, it's slower and less convenient. 

Btw. Ctrl+Left mouse still work but unnecessarily I must use keyboard+mouse oposite to only mouse, any chance to fix this?

**Comment by tophf** [comment]
That's easy to fix. The developer well need to add a listener for auxclick event.

**Comment by derjanb** [comment]
Fixed at the [latest beta version](http://tampermonkey.net/changelog.php?version=4.3.5359&ext=gcal).

**Comment by ArkadiuszMichalski** [comment]
Have you add any delay when display popup after click TM icon? After update to Chrome55 it's realy slowly, I have several other extensions and they display their popup immediately.

**Comment by derjanb** [comment]
> Have you add any delay when display popup after click TM icon? After update to Chrome55 it's realy slowly, I have several other extensions and they display their popup immediately.

@ArkadiuszMichalski No, it's a Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=649942

**Comment by tophf** [comment]
The Checker Plus extension author [found a workaround](https://crbug.com/673000#c6) for the delay issue:

>I was able to pinpoint the issue to the use of any <link> tags (css or import) in an extension popup window. The workaround I found was to dynamically insert the tags after a 1 millisecond delay. This allowed the popup to render quickly again.

**Comment by derjanb** [comment]
> TM's popup has one link and removing it fixes the delay issue according to my quick test on a locally modified copy of the extension.

Fixed at the [latest beta](http://tampermonkey.net/changelog.php?version=4.3.5371&ext=gcal).

**Comment by tophf** [comment]
>Fixed at the latest beta.

I'm still seeing the delay randomly.
Apparently, to circumvent this Chrome bug you need either to embed the style in html or insert it in DOMContentLoaded event callback.

**Comment by tophf** [comment]
Correction: I'm seeing the delay in Chrome 56+ (beta, dev, canary): they've "broken" `<style>` element just the same.
