### ISSUE TITLE
Google Drive login is constantly opened

### ISSUE THREAD

**Issue by Storm-Engineer** [Tampermonkey/tampermonkey#597]
Ever since I enabled cloud backup to Drive and logged in via my Google account, the logging in with google tab keeps getting opened. It is opened every time the browser starts, even though I'm already logged into my Google account, and if I close it without logging in again it will just re-open after a while.

## Expected Behavior
I should not be asked to log in with Google when I already have.

## Specifications

- Firefox: 62.0 (64-bit)
- TM: 4.8.5847
- OS: Arch Linux

**Comment by Remonell** [comment]
This problem is still up to date btw. 

Chrome 64-bit
Win10 64-bit

**Comment by genevera** [comment]
Still an issue.
Chrome MacOS

**Comment by derjanb** [comment]
I've investigated this a little bit an according to the documentation you should be asked only once:
https://developers.google.com/identity/protocols/OAuth2UserAgent#redirecting > OAUTH 2.0 ENDPOINTS > Parameters > prompt:

> Optional. A space-delimited, case-sensitive list of prompts to present the user. If you don't specify this parameter, the user will be prompted only the first time your app requests access.

Even the selected account should be remembered, which is working here as well. So I'm not sure why Google forgets your decision.

**Comment by genevera** [comment]
I wonder if it's AdNauseum borking it; that plus my ad-blocking dnsmasq config do cut out many google hostnames.

**Comment by joeytwiddle** [comment]
I'm getting this on both Firefox and Chrome. Sync seems to be working though. I run Ublock Origin in both browsers.

Any suggestions for how to debug?

I suppose I could disable Ublock for a week, and see if that affects the behaviour...

**Comment by joeytwiddle** [comment]
Chrome popped up a small window asking me to sign in. I tried to, but I got this message:

> Sign in with Google temporarily disabled for this app
>
> This app has not been verified yet by Google in order to use Google Sign In.

Perhaps this is relevant.

**Comment by joeytwiddle** [comment]
This is relevant to the not closing issue (Google Chrome):
```
oauth.php:7 Scripts may close only the windows that were opened by it.
```

But there is still the question why it keeps opening the authentication process in the first place.

**Comment by Remonell** [comment]
@joeytwiddle Did you make any progress solving this issue or finding out why it is misbehaving?

@derjanb Do you have any idea what the issue might be? Can we support you somehow by sending log data for example to figure this issue out?

**Comment by SmartManoj** [comment]
Meanwhile using hibernate mode

**Comment by SmartManoj** [comment]
Workaround
```
// ==UserScript==
// @name         TM sync
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://accounts.google.com/AccountChooser?*tampermonkey*

// @grant        none
// ==/UserScript==

(function() {
    'use strict';
document.querySelector('#choose-account-0').click();
    // Your code here...
})();
```

**Comment by anddam** [comment]
Still an issue with:

 * Chrome 76.0.3809.87 (Official Build) (64-bit)
 * TM: 4.8.41
 * OS: elementary OS 5.0 (Ubuntu 18.04 LTS based)

**Comment by SmartManoj** [comment]
@anddam So that the issue is still open

**Comment by derjanb** [comment]
This should be fixed at TM BETA 4.9.5967

Be sure to revoke the existing access token at the utilities tab in order to benefit from the fix.
![image](https://user-images.githubusercontent.com/767504/63961988-48631600-ca92-11e9-8d52-36a02efba72e.png)

https://chrome.google.com/webstore/detail/gcalenpjmijncebpfijmoaglllgpjagf
https://firefox.tampermonkey.net/firefox-current-beta.xpi

**Comment by Remonell** [comment]
@derjanb I freshly installed TamperMonkey Beta. On version 4.10.6104. This is still an issue and happens daily. Did everything you mentioned before.

**Comment by derjanb** [comment]
@Remonell can you please disable sync, restart Chrome, open Tampermonkey's background page (https://www.tampermonkey.net/faq.php#Q600), open the network tab and filter XHR requests? 
![image](https://user-images.githubusercontent.com/767504/70697862-99f08300-1cc6-11ea-8ef8-d833f72dc9df.png)

Then please enable sync again and sent a screenshot of the network and the console tab.

![image](https://user-images.githubusercontent.com/767504/70698161-3024a900-1cc7-11ea-85fa-77d822318d40.png)

Thanks.

**Comment by Remonell** [comment]
Hi Jan, thanks for taking your time. Here are the screenshots.

[https://ibb.co/42yJB16](https://ibb.co/42yJB16)

[https://ibb.co/VDHv4cp](https://ibb.co/VDHv4cp)

**Comment by derjanb** [comment]
Looks good. The problem (Google authentication screen) didn't happen when you made the screenshots, right?
Also please make sure "Log Level" is set to "Debug".

And next time please send the screenhsots via mail. When a re-authentication is done, they might contain sensitive data like access tokens.

**Comment by Remonell** [comment]
Correct, the authentication screen did not happen. Normally it happens when I boot up the computer in the morning plus randomly 2-3 times during the day (couldn't detect a certain pattern that triggers it).

I redid the procedure you described with the corrected loglevel. Same relevant output.

**Comment by BlueDrink9** [comment]
I'm still getting this as well on 4.9, but the beta fixed it. Is this intended? Or has the fix been released (chrome)

**Comment by BlueDrink9** [comment]
@derjanb has the beta fix mentioned here made it into regular releases yet?

**Comment by joeytwiddle** [comment]
Login screen is still opening for me, whenever I start Chrome or Firefox.

However I see in the [changelog](https://www.tampermonkey.net/changelog.php?version=4.9.6095&ext=fire):

> Use refresh tokens for less Google Drive re-authorization requests
> _Note: you need to revoke existing access tokens at the utilities tab to make use of this_

I will try it now...
![Screenshot_20200424_113034](https://user-images.githubusercontent.com/911799/80172284-3173c400-861f-11ea-9aa6-4fb53c77dbed.png)
