### ISSUE TITLE
Script not re-injecting on iframe redirect to mp4 URL

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#637]
Chromium 70.0.3538.110)
TM beta

I was trying to redirect from an iframe with a video player to the `src` mp4, which works, but in Chromium the script isn't re-injected in the redirected page. AFAICT, one way or another, either the browser or server resolves the mp4 redirect to the same iframe embed `src`, but it clearly loads a new page where the script should be reinjected. Works as expected in TM in Firefox.

Test URL: `https://bit.ly/2RlN9fj`

Another test (you have to choose Streamango as your server): `https://bit.ly/2shemRh`

Test Script:
```
// ==UserScript==
// @name         Test iframe redirect injection
// @version      0.1
// @include      /https?://stream(ango|cherry)\.*/*/
// @include      /https?://(.*\.)?fruithosted\.net/*/
// ==/UserScript==

var fruitHosted = new RegExp('^https?:\/\/(.*\.)?fruithosted\.net.*$');

if (window.location.href.match(fruitHosted)) {
    alert('Script Injected');
} else {
    document.getElementById('videooverlay').click();
    var vidSrc = document.getElementsByTagName('VIDEO')[0].getAttribute('src');
    location.href = vidSrc;
}
```

Edit: Updated include, looks like they shift between at least a couple domains. Wouldn't be great to use a wildcard though.

**Comment by narcolepticinsomniac** [comment]
BTW, getting rid of the redirect and creating a new iframe, then loading the mp4 in it, also fails to inject scripts in iframe in Chromium, but works in FF.

**Comment by tophf** [comment]
It looks like TM allows invalid regexps with unescaped `/` inside which is incorrect in JavaScript, but anyway the second regexp seems wrong as `/*` means zero or more slashes so maybe it should be `/?` or `/.*` assuming TM allows unescaped slashes.

**Comment by narcolepticinsomniac** [comment]
Yeah, that regex is trash, but that's besides the point. Unescaped backslashes aren't the only invalid syntax allowed in TM 'include' rules, so I've used and copypasta-reused a lot of syntax I know isn't great because it works. 

In that script above, the first include has zero issues in either browser, warts and all. The second include won't inject into an mp4 iframe redirect in Chromium. The same script works on the top level in Chromium, and it works on either the top level or iframe in FF.

If I switch to "valid" regex, I see the same exact results:

```
// ==UserScript==
// @name         Test iframe redirect injection
// @version      0.1
// @include      /https?://streamango\..*/
// @include      /https?://(.*\.)?fruithosted\.net/.*/
// ==/UserScript==

var fruitHosted = new RegExp('^https?:\/\/(.*\.)?fruithosted\.net.*$');

if (window.location.href.match(fruitHosted)) {
    alert('Script Injected');
} else {
    document.getElementById('videooverlay').click();
    var vidSrc = document.getElementsByTagName('VIDEO')[0].getAttribute('src');
    location.href = vidSrc;
}
```

Are you saying there's some version of regex where the second fruithosted rule actually works in an mp4 iframe redirect in Chromium?

**Comment by tophf** [comment]
Here's what happens for me in Chrome with TM as the only one extension enabled + this script:

0. go to https://bit.ly/2RlN9fj
1. click "not a robot"
2. click "Continue"
3. a grid of video thumbnails is shown (an ad, probably)
4. "Script injected" appears
5. the video (Ray Donovan) starts playing

**Comment by narcolepticinsomniac** [comment]
Huh. Yeah, I just checked Canary, and it does seem to work. I tested again in a clean Cent profile, and it doesn't work. I checked a clean Cent profile previously, and didn't think it was necessary to double-check Canary. Are you seeing it work in Cent?

**Comment by tophf** [comment]
I tested in Canary.
Turns out it was a bug in Chrome.
I've bisected the fix to https://crrev.com/c/1392503 (Chrome 73.0.3665.0).
BTW I'm not so sure anymore I'm not a robot...

@derjanb please check the commit and see if you can add a workaround for older versions of Chrome.

**Comment by narcolepticinsomniac** [comment]
Alright, good to know it'll be fixed eventually, but yeah, Chromium stable's still at v72. At the rate Cent's been lagging lately, it'll probably be quite a few months away.

>BTW I'm not so sure anymore I'm not a robot...

I always [kinda wondered](https://old.reddit.com/r/totallynotrobots/) that myself. =) Google's clearly trolling us at this point. [This extension](https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl) saves a lot of aggravation.

Thanks tophf.

**Comment by derjanb** [comment]
> I've bisected the fix to https://crrev.com/c/1392503 (Chrome 73.0.3665.0).

Wow, good catch. I have no ideas how to workaround this yet, because I don't see a way to know which Chrome parser handled the document and it's difficult to understand the patch without further knowledge of the general architecture. 
Maybe I could do some kind of MIME type sniffing, but this has to happen for all sub-frame requests?! Therefore I'm not sure whether it's worth the work, especially since it's fixed in newer Chrome. 🤔

**Comment by raszpl** [comment]
Same problem on Vivaldi (72.0.3626), made me thinks its https://github.com/greasemonkey/greasemonkey/issues/2574 related, because just as there renaming iframes into embeds somehow makes it work

**Comment by narcolepticinsomniac** [comment]
I know the original example in this issue was ignored because it was fixed in v73, but TM has other similar iframe injection issues which aren't. I'm still stuck on v72 currently, and the sheer amount of random script failures is baffling. Scripts which have worked for years, just randomly fail to inject, not just in iframes, but top level as well. If I reload the page, they inject. 

I've tested v73, and it seems to resolve all the top level issues, so perhaps v72 is just garbage. Regardless, TM still has an iframe injection issue from stable to Canary AFAICT.

Test URL: `https://bit.ly/2G0VNIA`

Test script:

```
// ==UserScript==
// @name         oload test script injection
// @version      0.1
// @include      /https?://(www\.)?o(pen)?load\..*\/embed\/.*/
// ==/UserScript==

alert("Script injected");
```

Click play to load the iframe. I'm seeing the same issue all over with these dynamically loaded iframes. The script loads with the iframe in Violentmonkey, but not TM.

**Comment by raszpl** [comment]
Im on Vivaldi (Chrome/73.0.3683.88) and its still broken.

>// @include      /https?://(www\.)?o(pen)?load\..*\/embed\/.*/

well now, this is exactly the host I have problems with ! :o This is the _only_ host I have problems with script injection into embedded frames.
Just as you said reloading a bunch of times finally makes the injection work, so does going into devtools and manually renaming iframe into embed, or deleting https: part of the address - basically forcing iframe reload after main page is already loaded <- this suggests some kind of timing problem/race condition.

**Comment by tophf** [comment]
In Chrome 72 lots of things are broken because of the new Network Service. You can disable it via `chrome://flags/#network-service` or by adding `--disable-features=NetworkService` to the command line.

**Comment by raszpl** [comment]
I disabled chrome://flags/#network-service as soon as Vivaldi switched to 72 build.

Thinking about it now Im pretty sure openload iframes worked just fine couple of months ago, so it must be a recent regression.

**Comment by narcolepticinsomniac** [comment]
Yeah, I already had it disabled. The most disturbing issue with v72 is the random top level injection failures. I can't repro with the same scripts in any previous or subsequent versions.

The last iframe injection failure example I provided definitely appears to be a TM issue though, seeing as how I can repro in every version of Chromium, and ViolentMonkey injects the script successfully.

**Comment by raszpl** [comment]
even `// @run-at document-start` doesnt help (I tried all run-at variants), you would think this would bypass anything server itself was pushing (some elaborate anti tempermoneky/script injection prevention BS).

**Comment by derjanb** [comment]
> Regardless, TM still has an iframe injection issue from stable to Canary AFAICT.
>
> Test URL: https://bit.ly/2G0VNIA
>
> Test script:
> ...

@narcolepticinsomniac 

I've tested with TM BETA 4.9.5921 and Chrome 74.0.3724.8. What I found is a UI issue that Tampermonkey states that the script was not executed yet when the iframe is reloaded/navigated to another URL.

Besides this the script is running fine so far. 

Two different scenarios:
1) no adblocker, no script blocker: after clicking at the frame and closing all pop-ups and so on the alert can be seen as expected
2) adblocker and scriptblocker enabled: after clicking at the iframe the alert can be seen for a very short period of time, but is closed when the iframe navigates to "https://oladblock.me/embed/...". You script is not setup to run at that URL and therefore no further alert is shown.

So besides the UI glitch, which will be fixed soon ;), everything seems to work fine. Do you see the same behavior?

**Comment by raszpl** [comment]
Try that a couple of times between different browser sessions. On both 4.8/73.0.3683.88 and 4.9.5921/73.0.3683.88 oload iframe is at best erratic. It might work every time, or it might not load at all until you force load iframe in a new tab first, or until you reload the page at least once. Once it triggers it will work reliably ~until you close the browser.

As for the UI glitch, I see it the other way around. TM keeps displaying [1] in extension Icon and showing "oload test script injection" as working _while script failed to load_.

It seems to be more reliable when I close all of my tabs(~100), but even then fails to catch embed at first browser start with just one page open ( https://bit.ly/2G7axV3 )

**Comment by narcolepticinsomniac** [comment]
>no adblocker

I suspected it might be some conflict, but ultimately, if it doesn't work with adblock, it doesn't work. Somehow ViolentMonkey manages to inject the script with the same adblock, so I'd expect TM to be able to as well.

>adblocker and scriptblocker enabled... the iframe navigates to "https://oladblock.me/embed/..."

Of course even weirder things happen if you also block all scripts, which I'm not doing. I'm never getting redirected to `oladblock.me`, so that must happen if you block javascript. The iframe source is an openload URL:

![oload](https://user-images.githubusercontent.com/14100003/55922428-07e02a00-5bcf-11e9-8dff-5d5ef730cab2.png)

and the script is not injected. The popup reflects that all applicable scripts are not only present, but active:

![TM Popup](https://user-images.githubusercontent.com/14100003/55922517-83da7200-5bcf-11e9-8ac6-48011178375c.png)

yet they are never injected.

This appears to only be an issue with iframes being loaded dynamically, because openload iframes which load with the page have no issues with script injection. When the script fails to inject, if I right click and select "reload iframe", the scripts are injected. I'm literally running a script in ViolentMonkey to reload iframes if an element injected by the other script doesn't exist, which works:

```
// ==UserScript==
// @name oload reload
// @namespace Violentmonkey Scripts
// @include      /https?://(www\.)?o(pen)?load\..*\/embed\/.*/
// @grant none
// ==/UserScript==

if (window !== window.top) {
  setTimeout(function() {
    var vid = document.getElementsByClassName('vid');
    if (!vid.length) {
      location.reload();
    }
  }, 2000);
}
```

If the original script hasn't run, the VM script reloads the iframe and the TM script does get injected.

I'm not using any form of NoScript. Besides [Fanboy's Ultimate list](https://www.fanboy.co.nz/r/fanboy-ultimate.txt), the only other possibly problematic subs would be the built-in uBO filters, some of which inject their own little scripts:

![uBO](https://user-images.githubusercontent.com/14100003/55923212-7b376b00-5bd2-11e9-8bbb-1c79aacfdae6.png)

If it is some conflict, it's still certainly odd that it only occurs in dynamically loaded iframes. Regardless of any redirects, any obfuscation, or how it's loaded, if the final destination `location.href` is a match for a script include, I expect the script to be injected. That is not the case in TM currently.

**Comment by raszpl** [comment]
I am beginning to understand what is going on. Steps to reproduce weirdness, no adblocks: 

Clean install Opera portable 58/71.0.3578.98 (was latest ~month ago), install TM v4.8.5890, , Install https://github.com/Tampermonkey/tampermonkey/issues/637#issuecomment-480061680 script, load https://bit.ly/2G7axV3. It will work 100% reliably _unless_ you quickly switch to another tab after clicking Refresh. Click Reload and then quickly open new tab, wait 10 seconds, switch back and:

-  no sign of our "Script injected" popup :(
-  TM icon says [1] and "This script was executed 1 time(s)".

Chrome 73 is different animal, Update/Clean install Opera portable 60/73.0.3683.86 with TM v4.8.5890, Install https://github.com/Tampermonkey/tampermonkey/issues/637#issuecomment-480061680 script, load https://bit.ly/2G7axV3, open devtools and focus on `<div id="player">` node where iframe is located. Now every Refresh you will get:

-  sometimes "Script injected" popup flashes for a split second and vanishes
-  iframe node in Devtools blinks 2-3 times, as if it was force loaded/initialized couple of times?
-  TM icon says [1] and "This script was executed 1 time(s)".

What changed between 71 and 73 is DOM is? no longer blocking on something? In 71 injecting the script blocked iframe from being refreshed (or refreshed it so quickly you couldnt notice?) _unless_ you quickly switched to another tab, being in the background didnt block and made injection fail. This explains why it wasnt reproducible on Chrome 71 with adblock - page with iframe was always the active tab.
In 73 that mysterious ?blocking behavior? is gone and iframe seemingly gets reinitialized couple of times during page load, but TM injection works only the first time (hence TM thinks it worked while popup quickly vanishes).

No idea if its oload host doing something shady intentionally[*], or if its a side effect of Chrome iframe DOM changes.


* Now, something I noticed some time ago and totally forgot to mention, but what might be the key. When debugging oload I'v seen them sometimes return empty html page with only one element - iframe embedding itself, this would go on 3 iframes deep until finally server returned real page and DOM rebuild on the fly.

**Comment by raszpl** [comment]
My tests from https://github.com/Tampermonkey/tampermonkey/issues/637#issuecomment-481957509 were all clean no adblockers Opera installs, so that cant be it unless Opera somehow uses uBO filters internally.

**Comment by narcolepticinsomniac** [comment]
Yep, fixed. Thanks derjanb! The original issue still exists in v72 but I guess since it's fixed in v73, it'll just be a browser bugs in that version. Cent should have a v73 beta in the next few days, and I'll be glad to get rid of v72. We can probably close this one.
