### ISSUE TITLE
Tampermonkey causes network requests to stall on pending state

### ISSUE THREAD

**Issue by damga** [Tampermonkey/tampermonkey#661]
(Please fill out the issue template with your details)

## Expected Behavior
Tampermonkey does nothing on sites that are not configured in any of the scripts

## Actual Behavior
Some time ago (days, weeks?) I noticed Login With Google stopped working in my browser
This happens because
https://accounts.google.com/o/oauth2/auth?* 
stalls on "pending".
The issue goes away when I disable Tampermonkey extension.
The issue is present on all websites that use Login With Google.

## Specifications

- Chrome Version 72.0.3626.121 (Official Build) (64-bit)
- TM: 4.8
- MacOS 10.14.3

## Script
The issue is present even with all scripts disabled

**Comment by derjanb** [comment]
I can not reproduce this. Please give me more context on what you are doing. Was Chrome opened recently or is it open quite a while? Do you have other tabs open?...

**Comment by derjanb** [comment]
NB: 
https://bugs.chromium.org/p/chromium/issues/detail?id=933470
https://bugs.chromium.org/p/chromium/issues/detail?id=931588

**Comment by derjanb** [comment]
From [issue 933470](https://bugs.chromium.org/p/chromium/issues/detail?id=933470):
> Setting chrome://flags/#network-service to Disabled fixes the issue

Can you please try that?

**Comment by derjanb** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=938560

**Comment by damga** [comment]
Flipping the flag solved the issue, thank you.

**Comment by derjanb** [comment]
@damga This is great news.

I'll keep this issue open until the underlying external issue is fixed.

**Comment by derjanb** [comment]
Can someone please set chrome://flags/#network-service to "Default" again and try it with Chrome 73 beta?

Thank you.

**Comment by damga** [comment]
Still does not work
MacOS
Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by derjanb** [comment]
Chrome 73 was released.

**Comment by kbuffington** [comment]
This issue is still occurring for me on Chrome 79.

In my instance it's been caused by a 302 redirect happening inside an XHR call on app startup:

![image](https://user-images.githubusercontent.com/2282004/73203370-89735b00-4102-11ea-8e18-b8e016cfb180.png)
(Yes, we have to call a "logout" endpoint while in the process of logging in)

![image](https://user-images.githubusercontent.com/2282004/73203495-c7707f00-4102-11ea-8b57-208935fd59c7.png)

As before, only the TM Chrome Extension needs to be enabled, no scripts are running. Seems to be a bit of a race condition as it's more likely to happen (99% of the time) if more Extensions are loaded, but the probably still occurs about 70-80% of the time when TM is the only one.

**Comment by hughfenghen** [comment]
This issue may be reintroduced in chrome79.

**Comment by Skiftcha** [comment]
still having this issue, disabling tampermonkey in chrome fixes it.
do not have #network-service flag to disable. only #network-service-in-process and it has no effect with any value

**Comment by Skiftcha** [comment]
now fixed in canary

**Comment by dilsonnn** [comment]
This issue is really frustating, I tried the BETA version but still not working.
Any news?

**Comment by derjanb** [comment]
The issue should be fixed at Chrome dev/canary (85.0.4175.0 or later) now.
https://bugs.chromium.org/p/chromium/issues/detail?id=938560#c29

**Comment by z-aki** [comment]
running into this error on Firefox 139.0.4 (64-bit) with tampermonkey  5.3.3
