### ISSUE TITLE
[Vivaldi] Twitter, Tweetdeck, Twitch not loading properly as long as Tampermonkey extension is enabled

### ISSUE THREAD

**Issue by KillyMXI** [Tampermonkey/tampermonkey#883]
## Expected Behavior

tweetdeck.twitter.com shows my decks,
twitter.com/{user} shows user tweets

## Actual Behavior

Yesterday the behavior changed to the following:

tweetdeck.twitter.com shows infinite spinner,
twitter.com/{user} shows the layout, but only error and retry buttons in place of content. ("Something went wrong. Try Again.")

browser console shows that all XHR requests to Twitter API are failed with net::ERR_FAILED

## Specifications

Vivaldi - 2.12.1843.5 (Official Build) (32-bit)
OS - Windows 10 OS Version 1909 (Build 18363.657)
JavaScript - V8 8.1.307.20

TM 4.9 (2019-11-15)

## Script

No scripts used for twitter pages

**Comment by Pathduck** [comment]
I can confirm the same behaviour. It also happens on `twitch.tv`. 
Requests to `https://gql.twitch.tv/gql` fail with the following headers:
```
Request URL: https://gql.twitch.tv/gql
Referrer Policy: no-referrer-when-downgrade

Provisional headers are shown
Accept-Language: en-GB
Client-Id: kimne78kx3ncx6brgo4mv6wki5h1ko
Content-Type: text/plain;charset=UTF-8
DNT: 1
Referer: https://www.twitch.tv/
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.41 Safari/537.36
X-Device-Id: 9ae71d0daaf1549e

[{operationName: "FrontPageNew_User", variables: {limit: 18}, extensions: {,…}},…]
0: {operationName: "FrontPageNew_User", variables: {limit: 18}, extensions: {,…}}
1: {operationName: "Prime_BlueBar_CurrentUser", variables: {,…}, extensions: {,…}}
2: {operationName: "Shelves",…}
```

Seems to affect all POST (JSON) operations. 

Vivaldi 2.12.1843.5 (latest snapshot) is based on Chromium 81 beta so I suspect the issue lies somewhere there. But could be worth looking into for Tampermonkey devs for when Chrome 81 is publicly available.

**Comment by aaaaadrien** [comment]
Same problem for me.
Workaround : use Good Twitter extension, and now, Twitter evert to old style but surf is okay

**Comment by derjanb** [comment]
Looks like this is a Vivaldi issue. 2.12.1843.5 is based on Chromium 81.0.4044.41, but Chome 81.0.4044.41 is working fine.

Working fine with 
* Vivaldi 
  * 2.11.1811.47 (Stable channel) (64-bit)
* Chrome
  * Version 80.0.3987.132
  * Version 81.0.4044.43 (Offizieller Build) beta (64-Bit)

Not working: 
* Vivaldi
  * 2.12.1843.5 (Official Build) (64-bit)

**Comment by KillyMXI** [comment]
Reported to Vivaldi, got issue reference VB-64468.

**Comment by Pathduck** [comment]
Fixed in latest Vivaldi Snapshot 2.12.1849.7. Tampermonkey is back enabled :)

**Comment by KillyMXI** [comment]
Yep, it is resolved now.

Relevant line in the change log:

> [Extensions][Regression] If an extension uses webrequest it could cause breakage on some websites: e.g. Twitter VB-64275

**Comment by derjanb** [comment]
Thanks for reporting this to Vivaldi.

**Comment by howar31** [comment]
This issue still exist in Chrome 85.0.4183.102 (64 bit).  I've tried:

- https://twitter.com
- https://open.spotify.com
- https://apps.apple.com/tw/app/id425073498
- https://hahow.in

are all failed.  Requests URI with `api.*` are all response net::ERR_FAILED when Tampermonkey enabled.

**Comment by Pathduck** [comment]
@howar31 It's not Tampermonkey doing this, check your ad-blocker settings. And this thread was related to a specific case in the Vivaldi browser, not Chrome.

**Comment by howar31** [comment]
I'm pretty sure it is Tampermonkey's issue since everything is working good after Tampermonkey being disabled, and error while it's enabled.  Tested in incognito mode on fresh installed Chrome.

I saw the symptoms are quite similar so I commented on this thread.  Sorry and I'll create a new issue to discuss about Chrome case if needed.

> @howar31 It's not Tampermonkey doing this, check your ad-blocker settings. And this thread was related to a specific case in the Vivaldi browser, not Chrome.

**Comment by KillyMXI** [comment]
> I'm pretty sure it is Tampermonkey's issue since everything is working good after Tampermonkey being disabled, and error while it's enabled.

And so I thought when opened this issue.
It was then confirmed by Vivaldi devs that it was on their side, as you can see from comments above.
It is totally possible Google devs did something similar this time.
(Browser developers are the ones responsible for the API and everything behind that allows extensions to exist, after all.)

Twitter and twitch work fine with up-to-date Vivaldi and Tampermonkey 4.10.

**Comment by FARHANE** [comment]
I have the same problem with the latest version of google chrome.
Google Chrome version: 86.0.4240.111 (Build officiel) (64 bits)
Tampermonkey: v4.11
