### ISSUE TITLE
can't sync via webdav when using Firefox

### ISSUE THREAD

**Issue by alston19** [Tampermonkey/tampermonkey#897]
Hi there, I'm using both Chrome and Firefox and want to sync Tampermonkey via webdav. It is a success when I use Chrome. However, "Action Failed" shows up when I use Firefox. Hope to fix the problem. THX.

## Expected Behavior
sync with FF

## Actual Behavior
error, "Action Failed".

## Specifications
![图片](https://user-images.githubusercontent.com/15274279/77906542-b4249000-72ba-11ea-9cf9-c844f82c6cd5.png)
![图片](https://user-images.githubusercontent.com/15274279/77906568-bedf2500-72ba-11ea-95af-6cc4e430442b.png)
![图片](https://user-images.githubusercontent.com/15274279/77906613-d28a8b80-72ba-11ea-95dd-bf32e5ff0cb6.png)

**Comment by BLaDZer** [comment]
I'm not sure if it is a related bug but: after configuring sync with Yandex Cloud - TM stop working and extension stuck at loading. Browser restart doesn't work

Specs:
Firefox 76.0.1, Windows 8.1 x64

**Console errors on extension loading:**
![изображение](https://user-images.githubusercontent.com/13044587/83334202-df752c80-a2b5-11ea-8767-6c0aee774380.png)

**Extension stuck on loading:**
![изображение](https://user-images.githubusercontent.com/13044587/83334050-e0598e80-a2b4-11ea-8aba-bf7a65aabcde.png)

**Comment by derjanb** [comment]
@BLaDZer Your issue should be fixed in 4.11.6117

**Comment by derjanb** [comment]
> I fixed it successfully by permited it work in privacy window in "about:addons" .

@NyaaGitty How are privacy windows related to the issue? What sync type are you using? WebDAV? If so, what software runs that webDAV server?

**Comment by YuruiHong** [comment]
I'm still experiencing the issue with syncing via WebDAV when using Firefox 140.5.0esr on Linux and Tampermonkey 5.4.0. I hope to reopen this issue for further assistance.

**Comment by derjanb** [comment]
@YuruiHong Please open a new issue and attach some network request debug, which shows what is wrong. Thanks.
