### ISSUE TITLE
Google sign in is shown everytime when logged into multiple google accounts

### ISSUE THREAD

**Issue by jacklul** [Tampermonkey/tampermonkey#904]
https://accounts.google.com/signin/oauth/oauthchooseaccount shows up when sync is starting (usually when browser is started), it seems to remember the auth data for like hour or so.

## Expected Behavior
This URL should not open each time browser is started.

## Actual Behavior
Mentioned URL opens almost every time browser starts.

## Specifications
- Chrome 80.0.3987.163
- TM: 4.9
- OS: Win 10 x64

From all extensions I'm using with Google Drive sync only Tempermonkey is having this issues.
(reddit enhanced, stylus)

I've already tried revoking access through the extension and Google Drive (with data wipe) as well as clean installing the extension without any success.

## Script

I've tried using this script I found while searching for solution but it doesn't work at all (doesn't show up as active script on that page):

```js
// ==UserScript==
// @name         Sync fix
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://*.google.com/*/oauthchooseaccount*tampermonkey*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    document.querySelector('div[data-authuser="0"]').click();
    window.close();
})();
```

**Comment by SmartManoj** [comment]
Remaining scripts working?

**Comment by jacklul** [comment]
> Remaining scripts working?

What do you mean? Posted script doesn't work on that page even though it should.

**Comment by SmartManoj** [comment]
Scripts on other pages.

**Comment by jacklul** [comment]
Everything is working fine on other pages

**Comment by jacklul** [comment]
Seems like the issue is back and resetting no longer works, now each time first attempt to authorize shows Google's "something went wrong page" and after clicking "Next" it ends up as "400. That's an error.'.

**Comment by joeytwiddle** [comment]
Thanks @jacklul, that script seems very useful. I have uploaded it here, so it's easy for people to install:

https://openuserjs.org/scripts/joeytwiddle/Tampermonkey_Google_Drive_sync_fix

**Comment by Neokyuubi** [comment]
I have the same problem !!!

**Comment by NgoKimPhu** [comment]
I found out the reason why the original script wasn't showing up as active: the match rule
```
// @match        *://*.google.com/*/oauthchooseaccount*tampermonkey*
```
did not match: if you open network tab in F12 you'll see that it redirects to `https://accounts.google.com/o/oauth2/auth?...`

**Comment by joeytwiddle** [comment]
For people still bothered by the popup, the issue was apparently fixed, but you need to revoke your existing tokens to enjoy the fix.

Instructions / screenshot here:

https://github.com/Tampermonkey/tampermonkey/issues/597#issuecomment-618782579

**Comment by Dominik-Reinert** [comment]
> For people still bothered by the popup, the issue was apparently **fixed**, but you need to **revoke your existing token** to enjoy the fix.

Hey @joeytwiddle , thanks for updating this, but I do not have this utilities tab in the tampermonkey v.13:

![image](https://user-images.githubusercontent.com/48657257/141062861-8d54bc81-6cec-4a97-9b2d-014944f91519.png)


![image](https://user-images.githubusercontent.com/48657257/141062914-aef24ca9-ff86-4032-a8c2-47b12671ffba.png)


do you have any tip? I cannot seem to find that revoking thing

**Comment by raceimaztion** [comment]
This has **never** _not_ been a problem for me. No matter how many times I try to restart the browser and revoke things, it has _never_ not asked me for the Google account to use.

I'm currently using v4.13, and revoking the access token actually fails sometimes.

On the Google Chrome installation that has two Google accounts, I have **never** _not_ been asked which account to use, nor have I _ever_ had the first attempt actually succeed. It always, **always** fails with an error 400.

**Comment by WhiteChairFromIkea** [comment]
This one started happening again about two months ago (chrome and tempermonkey are always up to date). Doing "access token" thing does not help at all, even it always says "success". (2021-Nov-15). The problem was here some year ago, but was fixed for some time. Now it annoys again :/

```
google chrome 96.0....
Tmnk 4.13
Windows 10 x64 up to date
```

**Comment by simon0117** [comment]
> Thanks @jacklul, that script seems very useful. I have uploaded it here, so it's easy for people to install:
> 
> https://openuserjs.org/scripts/joeytwiddle/Tampermonkey_Google_Drive_sync_fix

Using Tampermonkey on MacOS Safari when the Google login screen opens I get this in the JavaScript console:
`Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.
`

**Comment by Bazzu85** [comment]
So? Any news about a fix? I added the script mentioned at the top but the login request still appear every morning I turn on the work laptop..

**Comment by neokyuubi** [comment]
> So? Any news about a fix? I added the script mentioned at the top but the login request still appear every morning I turn on the work laptop..

Well, it's not clear but I have revoked the Google access and rest the sync and now it works (no login page required)

**Comment by simon0117** [comment]
I have switched to OneDrive, avoiding the Google Drive issue completely. -- Simon McClenahanOn Sep 19, 2022, at 5:15 AM, neokyuubi ***@***.***> wrote:﻿

So? Any news about a fix? I added the script mentioned at the top but the login request still appear every morning I turn on the work laptop..

Well, it's not clear but I have revoked the Google access and rest the sync and now it works (no login page required)

**Comment by L34T** [comment]
v4.19.6176 affected.

**Comment by FutureFlash94** [comment]
> For people still bothered by the popup, the issue was apparently **fixed**, but you need to **revoke your existing token** to enjoy the fix.
> 
> _**Edit:**_ I was wrong. It isn't fixed, at least not for everyone.
> 
> ![Screenshot_20200424_113034](https://user-images.githubusercontent.com/911799/80172284-3173c400-861f-11ea-9aa6-4fb53c77dbed.png)
> 
> Source: [#597 (comment)](https://github.com/Tampermonkey/tampermonkey/issues/597#issuecomment-526282634)

Thank you, this worked for me

**Comment by raceimaztion** [comment]
After _years_ of this problem, and trying to use this "Revoke Access Token" thing and logging in yet again (to absolutely _no_ success at any time), I finally don't have this problem.

But I don't know what's changed.

**Comment by vala84no** [comment]
Revoke Access Token just fails for me. It opens the same window and when I close it I have to select an account, leading back to the same page again, the Tampermonkey page then tells me it failed and the whole cycle repeats on the regular. It's completely unusable like this as it will bring up minimized windows and interrupt me every few minutes.

**Comment by derjanb** [comment]
@vala84no  here was an issue with the auth page yesterday. I hope it's working well now again?

**Comment by vala84no** [comment]
Yeah. I disabled the whole sync yesterday so I didn't think much of it, but re-enabling it today it seems to work. Thanks. 👍

**Comment by BoGnY** [comment]
Yes seems it works today 🤔🤷‍♂️

**Comment by DAOWAce** [comment]
Jeez, 3 years and this is still an issue.  I disabled tampermonkey a year or so ago because of it.

It's always been related to sync, but didn't know why it does it every browser start.

Trying the revoke access token option now..

**Comment by BoGnY** [comment]
> Jeez, 3 years and this is still an issue.  I disabled tampermonkey a year or so ago because of it.
> 
> It's always been related to sync, but didn't know why it does it every browser start.
> 
> Trying the revoke access token option now..

Revoke token and recreating it fix the problem

**Comment by joeytwiddle** [comment]
For people still suffering, please try this script:

https://greasyfork.org/en/scripts/403742-tampermonkey-google-drive-sync-fix-adopted

The tab will still pop up, but it will close itself. I have found this acceptable.

**Comment by DAOWAce** [comment]
Resetting the token worked, until now, when it started opening google sign-in again.

So, it didn't even last a month before it bugged up once again.

**Comment by hossein** [comment]
### I need an option to disable the tab-opening mechanism entirely.

I don't care if occasionally the background login fails because Google decided to ask me for my credentials for the 10th time in a day (happens to happen quite frequently for me).

The main issue is **apparently** (didn't check any code) even though the background login mode is implemented, opening a sign-in tab is still retained as a fallback mechanism or something for when the background sign-in fails.

And for some reason, even after a successful log-in, it continues to fall back to always opening a sign-in tab.

**Comment by derjanb** [comment]
Should be fixed at 5.1.6193 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by hossein** [comment]
Hello, can confirm this is fixed ever since I installed the beta.

I have had some forced re-log-ins by Google, but I observe that Tampermonkey beta did not open a sign-in tab and after logging in to Google in another tab (e.g if I first log into Gmail) then going to Tampermonkey settings and clicking "Userscript Sync -> Run Now" works without complaining about auth.

 I realized I was carried away a bit when writing my previous comment; thanks for the work derjanb and you guys put into the project :pray:

**Comment by brunocassol** [comment]
FYI this still happens for me. In Chrome.

**Comment by AndroidMaster25** [comment]
Still happening on Firefox Android
