### ISSUE TITLE
The header property in the GM_download accepts data in incorrect syntax and doesn't accept unsafe headers

### ISSUE THREAD

**Issue by 7nik** [Tampermonkey/tampermonkey#997]
The docs say that `headers` in the GM_download are the same as in the GM_XHR (though docs don't specify how the headers must be passed, there are enough examples on the internet). But in fact, `headers` for GM_download have the syntax of `headers` of `chrome.downloads.download`.

Also, headers like `"User-Agent"` aren't allowed.

## Expected Behavior
```
GM_download({
    ....,
    headers: { "Header1-Name": "Header1-Value", "Header2-Name": "Header2-Value" },
});
```

## Actual Behavior
```
GM_download({
    ....,
    headers: [ { name: "Header1-Name", value: "Header1-Value" }, { name: "Header2-Name", value: "Header2-Value" } ],
});
```

## Specifications

- Chromium: Version 83.0.4103.97 (Official Build) Arch Linux (64-bit)
- TM: stable, 4.10
- OS: Manjaro Linux (64-bit)

## Script

```js
// ==UserScript==
// @name         Test Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://github.com/*
// @grant        GM_download
// @connect      httpbin.org
// ==/UserScript==

(function() {
    // expected syntax of headers
    GM_download({
        url: "https://httpbin.org/headers",
        name: "test1.txt",
        headers: { "Accept-Language": "en-US" },
        onprogress: () => console.log("Expected headers works"),
    });
    // actual syntax of headers
    GM_download({
        url: "https://httpbin.org/headers",
        name: "test2.txt",
        headers: [{ name: "Accept-Language", value: "en-US" }],
        onprogress: () => console.log("Regular headers works"),
    });
    // but it doesn't allow to set unsafe headers
    GM_download({
        url: "https://httpbin.org/headers",
        name: "test3.txt",
        headers: [{ name: "User-Agent", value: "qwerty" }],
        onprogress: () => console.log("Unsafe headers works"),
    });
})();
```

**Comment by 7nik** [comment]
Also, looks like `onload` listener receives an empty object.

**Comment by 7nik** [comment]
```js
    GM_download({
        url: "https://httpbin.org/delay/2",
        name: "test1.txt",
    }).abort();
```
I'm not sure whether it should abort but for me, it usually doesn't.
And it saves with name test1.**json**.

**Comment by 7nik** [comment]
Oh, yeah, it's all for download mode browser API.

For native mode, headers and abort works correctly, even undocumented property `timeout` works. Though `onerror` isn't called when a user cancels downloading.

**Comment by derjanb** [comment]
Fixed at TM BETA 4.11.6116

**Comment by 7nik** [comment]
In browser mode, the first call still doesn't work, but the third one now works. And according to response, now the headers aren't applied at all.

**Comment by derjanb** [comment]
> And according to response, now the headers aren't applied at all.

Headers are now GM_xhr compliant (also in "Browser API" mode) -> 
```JS 
{ "Accept-Language": "en-US" }
```

**Comment by 7nik** [comment]
What about getting the data via fetch and saving it as a blob when unsafe headers need to be used?
I believe stream API can be used for large (or all) files.
